---
by_key:
  # Mounts (also bound to keys)
  P2_R: m fav  # C_MountJournal.Pickup(0)
  L2_R: m yak  # s 122708
  L1_R: m ah  # s 465235

  # Dragon Riding
  R1_D: s 372608
  R2_D: s 425782
  S_D: s 374990
  X_D: s 372610
  T_D: s 465235
  C_D: s 436854
  L1_R1_D: s 361584
  L1_R2_D: m dis  # dismount
  L1_X_D: s 403092
  L1_T_D: s 122708

  L1_L: m rac1
  L1_D: m t13
  L1_U: m t14

  # also bound to a key
  L2_L: m gc  # cancel some auras (slow fall etc.)

  # this doesn't work for warlock's new healthstones
  L2_D: m hs  # healthstone

  L2_U: m rac2

  P2_L: m mana
