---
by_key:
  L2_L1_R1: m ffsb
  L2_R1: s "Typhoon"  # self ursol's
  L2_P2_R1: m dcs  # clone/soothe

  L2_L1_R2: m dirmb
  L2_R2: m root  # mass root / ursol's
  L2_P2_R2: s "Entangling Roots"

  L1_S_B: s "Growl"
  P2_S: s "Moonfire"
  L2_P2_S: s "Starfire"
  S_B: s "Frenzied Regeneration"

  L2_X: s "Heart of the Wild"
  L1_P2_X: m suv  # self ursol's

  L2_L1_T: s "Dash"
  L2_T: m ffr
  T_1: m swg
  T_2: s "Wild Growth"
  T_B: m swg
  T_C: m swg
  T_M: m swg
  P2_T: s "Stampeding Roar"
  L1_P2_T: s "Frenzied Regeneration"
  L2_P2_T: m ffs

  L2_L1_C: m wch  # cancel + jump to teammate button
  L2_C: m ffm
  C_1: s "Wild Charge"
  C_2: s "Wild Charge"
  C_B: s "Wild Charge"
  C_C: s "Wild Charge"
  C_M: s "Wild Charge"
  P2_C: s "Barkskin"
  L1_P2_C: s "Rebirth"

  P2_P3: m flap  # boomkin / flap (macro)
  L2_P3: m prow  # prowl (macro)
  L1_P3: m cat  # cat form (macro)

  L2_L1_P1: m cf  # cancel form (macro)
  L2_P1: m bear  # bear form (macro)
  L1_P1: m trav  # travel form (macro)

  P2_D: m motw  # mark of the wild (macro)

  P2_U: s "Revive"

  # cancel macro override (has dedicated bind)
  # L2_L: ""
  L2_U: s "Symbiotic Relationship"

  # mount button overrides
  L2_P2_C: s "Hibernate"
  # L2_R: m dirmb
  # L1_R: s "Nature's Vigil"
