---
by_key:
  L2_L1_R1: s "Quell"
  L2_R1: s 357208  # Fire Breath
  L2_P2_R1: s "Sleep Walk"

  L2_L1_R2: s "Landslide"
  L2_P2_R2: s "Deep Breath"
  L1_P2_R2: s "Oppressing Roar"

  L2_P2_S: s "Fury of the Aspects"

  L1_X_1: m scf
  L1_X_2: s "Cauterizing Flame"
  P2_X: s "Obsidian Scales"

  L1_P2_R1: s "Tip the Scales"

  L2_T: s "Zephyr"
  L1_T_1: s "Tail Swipe"
  L1_T_2: s "Tail Swipe"
  T_1: m sts
  T_2: s "Time Stop"
  P2_T: s "Chrono Loop"

  L2_P2_T: s "Source of Magic"
  # L1_P2_T: s "Unravel"

  L2_L1_P1: m tssp
  L2_P1: s "Rescue"
  L1_P1: s "Hover"

  L2_P3: s "Swoop Up"

  P2_D: s "Blessing of the Bronze"
  P2_U: s "Return"

  L2_R: s 360022  # "Chosen Identity"
  L1_R: s "Visage"
