---
by_key:
  L2_L1_R1: s "Quell"
  L2_P2_R1: s "Sleep Walk"

  L2_L1_R2: s "Landslide"
  L2_P2_R2: s "Deep Breath"
  L1_P2_R2: s "Oppressing Roar"

  L1_P2_X: s "Fury of the Aspects"

  L1_X_1: m scf
  L1_X_2: s "Cauterizing Flame"

  P2_S: s "Chrono Loop"

  P2_X: s "Tip the Scales"

  L1_T_1: m sts
  L1_T_2: s "Time Stop"

  T_1: s "Renewing Blaze"
  T_2: s "Renewing Blaze"

  L1_P2_T: s "Source of Magic"

  C_1: s "Obsidian Scales"
  C_2: s "Obsidian Scales"

  P2_C: s "Tail Swipe"

  L1_P2_C: s "Visage"

  L2_L1_P1: s "Time Spiral"
  L2_P1: s "Rescue"
  L1_P1: s "Hover"

  L2_P3: s "Swoop Up"
  L1_P3: s "Zephyr"

  P2_D: s "Blessing of the Bronze"
  P2_U: s "Return"
