---
by_key:
  L2_L1_R1: s "Spear Hand Strike"
  L2_P2_R1: s "Paralysis"

  P2_R2: s "Disable"
  L2_P2_R2: 's "Transcendence: Transfer"'
  L1_P2_R2: s "Crackling Jade Lightning"

  L1_S_1: m srop
  L1_S_2: m rop

  L2_X: s "Fortifying Brew"

  X_1: m stl
  X_2: s "Tiger's Lust"
  # P2_X: s "Fortifying Brew"

  L1_P2_X: s "Provoke"

  L1_P2_C: s "Zen Flight"

  L1_P2_T: s "Zen Pilgrimage"

  L2_L1_P1: s "Touch of Death"
  L2_P1: s "Leg Sweep"
  L1_P1: s "Roll"

  P2_D: s "Transcendence"

  P2_U: s "Resuscitate"
