---
array:
  - [1, "C_Spell.PickupSpell(115175)"]
  - [2, "C_Spell.PickupSpell(115151)"]
  - [3, "C_Spell.PickupSpell(115450)"]
  - [4, "C_Spell.PickupSpell(322101)"]
  - [5, "C_Spell.PickupSpell(119996)"]
  - [6, "C_Spell.PickupSpell(116841)"]
  - [7, "C_Spell.PickupSpell(116670)"]
  - [8, "C_Spell.PickupSpell(124682)"]
  - [9, "C_Spell.PickupSpell(115313)"]
  - [10, "C_Spell.PickupSpell(388615)"]
  - [11, "C_Spell.PickupSpell(101643)"]
  - [12, "C_Spell.PickupSpell(116849)"]
  - [13, "PickupMacro(120 + 2)"]
  - [14, "PickupMacro(120 + 8)"]
  - [15, "PickupMacro(120 + 4)"]
  - [16, "C_Spell.PickupSpell(322101)"]
  - [17, "C_Spell.PickupSpell(119996)"]
  - [18, "PickupMacro(120 + 9)"]
  - [19, "PickupMacro(120 + 5)"]
  - [20, "PickupMacro(120 + 3)"]
  - [21, "PickupMacro(120 + 7)"]
  - [22, "C_Spell.PickupSpell(388615)"]
  - [23, "C_Spell.PickupSpell(101643)"]
  - [24, "PickupMacro(120 + 10)"]
  - [25, "C_Spell.PickupSpell(100784)"]  # blackout kick
  - [26, "C_Spell.PickupSpell(117952)"]  # crackling lightning
  - [28, "C_Spell.PickupSpell(115546)"]
  - [32, "C_Spell.PickupSpell(115008)"]
  - [38, "C_Spell.PickupSpell(119381)"]
  - [41, "C_Spell.PickupSpell(212051)"]
  - [44, "C_Spell.PickupSpell(115078)"]
  - [49, "C_Spell.PickupSpell(101546)"]  # spinning crane kick
  - [50, "C_Spell.PickupSpell(100780)"]  # tiger palm
  - [55, "C_Spell.PickupSpell(116680)"]
  - [56, "C_Spell.PickupSpell(116095)"]
  - [57, "C_Spell.PickupSpell(122783)"]
  - [58, "C_Spell.PickupSpell(115203)"]
  - [59, "C_Spell.PickupSpell(115294)"]
  - [61, "C_Spell.PickupSpell(107428)"]
  - [62, "C_Spell.PickupSpell(116844)"]
  - [63, "C_Spell.PickupSpell(322109)"]  # tod
  - [64, "C_Spell.PickupSpell(325197)"]  # chi-ji
  - [67, "C_Spell.PickupSpell(116705)"]
  - [68, "PickupMacro(120 + 6)"]
