---
array:
  - [1, "C_Spell.PickupSpell(184575)"]
  - [2, "C_Spell.PickupSpell(383328)"]
  - [3, "PickupMacro(120 + 2)"]
  - [4, "PickupMacro(120 + 7)"]
  - [5, "C_Spell.PickupSpell(403876)"]
  - [6, "PickupMacro(120 + 5)"]
  - [7, "C_Spell.PickupSpell(20271)"]
  - [8, "C_Spell.PickupSpell(53385)"]
  - [9, "PickupMacro(120 + 4)"]
  - [10, "PickupMacro(120 + 3)"]
  - [11, "C_Spell.PickupSpell(184662)"]
  - [12, "C_Spell.PickupSpell(642)"]
  - [13, "C_Spell.PickupSpell(210256)"]
  - [14, "C_Spell.PickupSpell(6940)"]
  - [15, "C_Spell.PickupSpell(85673)"]
  - [16, "C_Spell.PickupSpell(19750)"]
  - [17, "C_Spell.PickupSpell(403876)"]
  - [18, "C_Spell.PickupSpell(1044)"]
  - [19, "C_Spell.PickupSpell(62124)"]
  - [20, "C_Spell.PickupSpell(391054)"]
  - [21, "C_Spell.PickupSpell(1022)"]
  - [22, "C_Spell.PickupSpell(633)"]  # 471195
  - [23, "C_Spell.PickupSpell(184662)"]
  - [24, "C_Spell.PickupSpell(642)"]
  - [25, "C_Spell.PickupSpell(853)"]
  - [26, "C_Spell.PickupSpell(410126)"]
  - [31, "C_Spell.PickupSpell(32223)"]
  - [32, "C_Spell.PickupSpell(190784)"]
  - [37, "C_Spell.PickupSpell(317920)"]
  - [38, "C_Spell.PickupSpell(210256)"]

  - [41, "C_Spell.PickupSpell(5502)"]

  - [43, "C_Spell.PickupSpell(465)"]
  - [46, "C_Spell.PickupSpell(7328)"]
  # - [47, "MACRO"] ?
  - [49, "C_Spell.PickupSpell(115750)"]
  - [50, "C_Spell.PickupSpell(6940)"]
  # - [54, "MACRO"] ?
  - [55, "C_Spell.PickupSpell(255937)"]
  - [56, "C_Spell.PickupSpell(375576)"]
  - [61, "C_Spell.PickupSpell(24275)"]
  - [62, "C_Spell.PickupSpell(343721)"]
  - [67, "C_Spell.PickupSpell(96231)"]
  - [68, "PickupMacro(120 + 6)"]
