---
by_key:
  L2_L1_R1: s "Wind Shear"
  L2_R1: m pgp
  L2_P2_R1: s "Hex"

  L2_L1_R2: s "Grounding Totem"
  L2_P2_R2: s "Lightning Lasso"
  P2_R2: s "Frost Shock"
  L1_P2_R2: s "Nature's Swiftness"

  L1_S_1: m sct
  L1_S_2: s "Capacitor Totem"
  L2_S: s "Ascendance"
  L2_P2_S: s "Bloodlust"

  L2_L1_X: s "Unleash Shield"
  L2_X: s "Static Field Totem"
  X_1: m stp
  X_2: s "Totemic Projection"
  P2_X: s "Healing Stream Totem"
  L2_P2_X: s "Water Walking"
  L1_P2_X: s "Totemic Recall"

  L2_T: s "Wind Rush Totem"
  P2_T: s "Tremor Totem"
  L2_P2_T: m ses
  L1_P2_T: s "Earth Shield"

  L2_L1_C: s "Burrow"
  L2_C: s "Earthgrab Totem"
  L1_C_1: m st
  L1_C_2: s 51490  # "Thunderstorm"
  P2_C: s "Astral Shift"
  L1_P2_C: s "Stone Bulwark Totem"

  P2_P3: s "Poison Cleansing Totem"
  L2_P3: s "Earth Elemental"
  L1_P3: s "Counterstrike Totem"

  L2_L1_P1: s "Spiritwalker's Grace"
  L2_P1: m swgw
  L1_P1: s "Ghost Wolf"

  P2_D: m ssf
  P2_U: s "Ancestral Spirit"
  L2_R: s "Flametongue Weapon"
  L1_R: s "Lightning Shield"
