---
array:
  # PADRSHOULDER column
  - [67, C_Spell.PickupSpell("Wind Shear")]
  - [49, C_Spell.PickupSpell("Hex")]

  # PADRTRIGGER column
  - [68, C_Spell.PickupSpell("Grounding Totem")]
  - [50, C_Spell.PickupSpell("Lightning Lasso")]
  - [26, C_Spell.PickupSpell("Greater Purge")]

  # PAD3 column
  - [27, C_Spell.PickupSpell(2825)]  # "Bloodlust"

  # PAD1 column
  - [58, C_Spell.PickupSpell("Astral Shift")]
  - [52, C_Spell.PickupSpell("Water Walking")]
  - [28, PickupMacro(120 + 3)]

  # PAD4 column
  - [59, C_Spell.PickupSpell("Ancestral Guidance")]

  # PAD2 column
  - [72, C_Spell.PickupSpell("Stone Bulwark Totem")]

  # paddles (right)
  - [32, C_Spell.PickupSpell("Ghost Wolf")]

  # d-pad (down)
  - [46, PickupMacro(120 + 4)]  # skyfury buff
