---
cvars:
  GamePadEnable: 1
  GamePadEmulateAlt: "PADPADDLE2"
  GamePadEmulateShift: "PADLSHOULDER"
  GamePadEmulateCtrl: "PADLTRIGGER"
  GamePadRunThreshold: 0
  GamePadCameraYawSpeed: 1.75
  advancedCombatLogging: 1

# ALT-SHIFT
# ALT-CTRL
# CTRL-SHIFT

bindings:
  - command: TARGETFOCUS
    key: PADDLEFT
  - command: MULTIACTIONBAR4BUTTON9
    key: PADDLEFT
    modifiers: [ALT]
  - command: MULTIACTIONBAR3BUTTON9
    key: PADDLEFT
    modifiers: [SHIFT]
  - command: MULTIACTIONBAR4BUTTON3
    key: PADDLEFT
    modifiers: [CTRL]
  - command: FOCUSTARGET
    key: PADDLEFT
    modifiers: [CTRL, SHIFT]

  - command: TARGETNEARESTFRIENDPLAYER
    key: PADDDOWN
  - command: MULTIACTIONBAR4BUTTON10
    key: PADDDOWN
    modifiers: [ALT]
  - command: MULTIACTIONBAR3BUTTON10
    key: PADDDOWN
    modifiers: [SHIFT]
  - command: MULTIACTIONBAR4BUTTON4
    key: PADDDOWN
    modifiers: [CTRL]
  - command: TARGETPREVIOUSFRIENDPLAYER
    key: PADDDOWN
    modifiers: [CTRL, SHIFT]

  - command: TARGETNEARESTENEMYPLAYER
    key: PADDUP
  - command: MULTIACTIONBAR4BUTTON11
    key: PADDUP
    modifiers: [ALT]
  - command: MULTIACTIONBAR3BUTTON11
    key: PADDUP
    modifiers: [SHIFT]
  - command: MULTIACTIONBAR4BUTTON5
    key: PADDUP
    modifiers: [CTRL]
  - command: TARGETNEARESTENEMY
    key: PADDUP
    modifiers: [CTRL, SHIFT]
  - command: TARGETSCANENEMY
    key: PADDUP
    modifiers: [ALT, SHIFT]

  - command: ASSISTTARGET
    key: PADDRIGHT
  - command: MULTIACTIONBAR4BUTTON12
    key: PADDRIGHT
    modifiers: [ALT]
  - command: MULTIACTIONBAR3BUTTON12
    key: PADDRIGHT
    modifiers: [SHIFT]
  - command: MULTIACTIONBAR4BUTTON6
    key: PADDRIGHT
    modifiers: [CTRL]
  - command: TARGETLASTTARGET
    key: PADDRIGHT
    modifiers: [CTRL, SHIFT]

  - command: FRIENDNAMEPLATES
    key: PADLSTICK
  - command: NAMEPLATES
    key: PADRSTICK

  - command: TOGGLE_VOICE_SELF_MUTE
    key: PADLSTICK
    modifiers: [ALT]
  - command: TOGGLE_VOICE_SELF_DEAFEN
    key: PADRSTICK
    modifiers: [ALT]

  - command: CAMERAZOOMOUT
    key: PADLSTICK
    modifiers: [SHIFT]
  - command: CAMERAZOOMIN
    key: PADRSTICK
    modifiers: [SHIFT]

  - command: TOGGLESHEATH
    key: PADLSTICK
    modifiers: [CTRL]
  - command: TOGGLEFPS
    key: PADRSTICK
    modifiers: [CTRL]

  - command: FLIPCAMERAYAW
    key: PADLSTICK
    modifiers: [CTRL, SHIFT]
  - command: CENTERCAMERA
    key: PADRSTICK
    modifiers: [CTRL, SHIFT]

  - command: TOGGLEUI
    key: PADLSTICK
    modifiers: [ALT, SHIFT]
  - command: SCREENSHOT
    key: PADRSTICK
    modifiers: [ALT, SHIFT]

keymap:
  PADRTRIGGER: BUTTON4
  PADRSHOULDER: BUTTON5
  PAD1: S
  PAD2: R
  PAD3: Q
  PAD4: 3

  PADDLEFT: 2
  PADDUP: MOUSEWHEELUP
  PADDDOWN: MOUSEWHEELDOWN
  PADDRIGHT: 4

  PADLSTICK: T
  PADRSTICK: V

  PADBACK: Z
  PADSYSTEM: X
  PADFORWARD: C

  PADPADDLE1: SPACE
  PADPADDLE2: ALT
  PADPADDLE3: F
  PADPADDLE4: 1
