---
global:
  # Mounts
  - [48, "C_MountJournal.Pickup(0)"]
  - [42, "C_Spell.PickupSpell(122708)"]
  - [36, "C_Spell.PickupSpell(465235)"]

  # Dragon Riding
  - [121, "C_Spell.PickupSpell(372608)"]
  - [122, "C_Spell.PickupSpell(425782)"]
  - [123, "C_Spell.PickupSpell(374990)"]
  - [124, "C_Spell.PickupSpell(372610)"]
  - [125, "C_Spell.PickupSpell(465235)"]
  - [126, "C_Spell.PickupSpell(436854)"]
  - [127, "C_Spell.PickupSpell(361584)"]
  - [128, "PickupMacro(4)"]
  - [130, "C_Spell.PickupSpell(403092)"]
  - [131, "C_Spell.PickupSpell(122708)"]

  # Macros
  - [33, "PickupMacro(3)"]
  - [34, "PickupMacro(1)"]
  - [35, "PickupMacro(2)"]
  - [40, "PickupMacro(7)"]

classes:
  WARRIOR: []
  PALADIN: []
  HUNTER: []
  ROGUE: []
  PRIEST: []
  DEATHKNIGHT: []
  SHAMAN: []
  MAGE: []
  WARLOCK: []
  MONK: []

  DRUID:
    # Rejuvenation
    - [1, "C_Spell.PickupSpell(774)"]
    # Regrowth
    - [2, "C_Spell.PickupSpell(8936)"]

    # Wild Growth
    - [5, "C_Spell.PickupSpell(48438)"]
    # Wild Charge
    - [6, "C_Spell.PickupSpell(102401)"]

    # Rejuvenation
    - [13, "PickupMacro(120 + 11)"]
    # Regrowth
    - [14, "PickupMacro(120 + 15)"]

    # Wild Growth
    - [17, "PickupMacro(120 + 12)"]
    # Wild Charge [help]
    - [18, "PickupMacro(120 + 7)"]

  DEMONHUNTER: []
  EVOKER: []

specializations:
  # Druid - Restoration
  105:
    # Remove Corruption
    - [3, "C_Spell.PickupSpell(88423)"]
    # Cenarion Ward
    - [4, "C_Spell.PickupSpell(102351)"]
    # Lifebloom
    - [7, "C_Spell.PickupSpell(33763)"]
    # Grove Guardians
    - [8, "C_Spell.PickupSpell(102693)"]
    # Efflorescence
    - [9, "C_Spell.PickupSpell(145205)"]
    # Swiftmend
    - [10, "C_Spell.PickupSpell(18562)"]
    # Overgrowth
    - [11, "C_Spell.PickupSpell(203651)"]
    # Ironbark
    - [12, "C_Spell.PickupSpell(102342)"]

    # Remove Corruption
    - [15, "PickupMacro(120 + 9)"]
    # Cenarion Ward
    - [16, "PickupMacro(120 + 16)"]
    # Lifebloom
    - [19, "PickupMacro(120 + 8)"]
    # Grove Guardians
    - [20, "PickupMacro(120 + 18)"]
    # Efflorescence
    - [21, "PickupMacro(120 + 20)"]
    # Swiftmend
    - [22, "PickupMacro(120 + 13)"]
    # Overgrowth
    - [23, "PickupMacro(120 + 14)"]
    # Ironbark
    - [24, "PickupMacro(120 + 17)"]

    - [25, "C_Spell.PickupSpell(5176)"]
    - [26, "C_Spell.PickupSpell(740)"]
    - [49, "C_Spell.PickupSpell(33786)"]
    - [50, "C_Spell.PickupSpell(339)"]

    - [55, "C_Spell.PickupSpell(197626)"]

    - [57, "C_Spell.PickupSpell(8921)"]
    - [58, "C_Spell.PickupSpell(108238)"]
    - [59, "C_Spell.PickupSpell(106898)"]
    - [60, "C_Spell.PickupSpell(22812)"]
    - [61, "C_Spell.PickupSpell(132469)"]

    - [63, "C_Spell.PickupSpell(197628)"]
    - [64, "C_Spell.PickupSpell(319454)"]
    - [65, "C_Spell.PickupSpell(1850)"]
    - [66, "C_Spell.PickupSpell(20484)"]
    - [67, "C_Spell.PickupSpell(33891)"]

    # Nature's Swiftness
    - [56, "C_Spell.PickupSpell(132158)"]

    # Ursol's Vortex
    - [62, "C_Spell.PickupSpell(102793)"]
    - [68, "PickupMacro(120 + 19)"]

    # Forms
    - [44, "PickupMacro(120 + 5)"]
    - [38, "PickupMacro(120 + 3)"]
    - [32, "PickupMacro(120 + 4)"]
    - [31, "PickupMacro(120 + 2)"]
    - [37, "PickupMacro(120 + 1)"]

    - [41, "C_Spell.PickupSpell(212040)"]
    - [46, "PickupMacro(120 + 10)"]

    # Bear Form
    - [97, "C_Spell.PickupSpell(33917)"]
    - [98, "C_Spell.PickupSpell(8936)"]
    - [99, "C_Spell.PickupSpell(192081)"]
    - [100, "C_Spell.PickupSpell(213764)"]
    - [102, "C_Spell.PickupSpell(102401)"]
    - [103, "C_Spell.PickupSpell(22842)"]
    - [104, "C_Spell.PickupSpell(102693)"]
    - [105, "C_Spell.PickupSpell(6795)"]

    # Cat Form
    - [73, "C_Spell.PickupSpell(5221)"]
    - [74, "C_Spell.PickupSpell(8936)"]
    - [75, "C_Spell.PickupSpell(22570)"]
    - [76, "C_Spell.PickupSpell(213764)"]
    - [78, "C_Spell.PickupSpell(102401)"]
    - [79, "C_Spell.PickupSpell(1822)"]
    - [80, "C_Spell.PickupSpell(102693)"]
    - [81, "C_Spell.PickupSpell(1079)"]
    - [82, "C_Spell.PickupSpell(22568)"]
