---
name: gnomish-army-knife
version: "{{major}}.{{minor}}.{{patch}}"
description: World of Warcraft polyfills and standardization.
entry: {{entry}}

requirements:
  - vcorelib>=3.5.0
  - runtimepy>=5.10.1

dev_requirements:
  - setuptools-wrapper
  - types-setuptools

commands:
  - name: markdown
    description: "generate Markdown content from class data"
  - name: scan
    description: "scan the 'World of Warcraft' directory for updates"

init_local: |
  PKG_SLUG = PKG_NAME.replace("-", "_")
  PKG_ABBREV = "gak"
  DEFAULT_CONFIG = f"{PKG_ABBREV}.yaml"
  WOW_DIR = "World of Warcraft"

mypy_local: |
  [mypy-aiofiles.*]
  ignore_missing_imports = True

ci_local:
  - "- run: mk python-editable"
