---
name: gnomish-army-knife
version: "{{major}}.{{minor}}.{{patch}}"
description: Software tools for WoW arena analysis.
entry: {{entry}}
requirements:
  - vcorelib
dev_requirements:
  - setuptools-wrapper
  - types-setuptools
