---
# 6
by_name:
  sdad:
    body: |-
      #showtooltip
      /cast [@player] Death and Decay

  sams:
    body: |-
      #showtooltip
      /cast [@player] Anti-Magic Shell

  samz:
    body: |-
      #showtooltip
      /cast [@player] Anti-Magic Zone

  pdc:
    body: |-
      #showtooltip
      /cast [@pet] Death Coil

  sdc:
    body: |-
      #showtooltip
      /cast [@player] Death Coil
