---
# 12
array:
  - name: self
    body: |-
      #showtooltip
      /cast [@player] Metamorphosis

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Sigil of Misery

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Sigil of Flame

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Sigil of Spite

  - name: badge
    body: |-
      #showtooltip Eye Beam
      /use 14
      /cast Eye Beam
