---
# 12
array:
  - name: self
    body: |-
      #showtooltip
      /cast [@player] Metamorphosis

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Sigil of Misery

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Sigil of Flame
