---
# 11
by_name:
  trav:
    body: |-
      #showtooltip
      /cast [indoors] !Cat Form; !Travel Form

  prow:
    body: |-
      #showtooltip Prowl
      /cast [nocombat] !Prowl
      /changeactionbar 1

  cat:
    body: |-
      #showtooltip Cat Form
      /cast [noform:2] Cat Form
      /changeactionbar 1

  bear:
    body: |-
      #showtooltip Bear Form
      /cast [noform:1] Bear Form
      /changeactionbar 1

  beam:
    body: |-
      #showtooltip
      /cast Solar Beam
      /cast Mass Entanglement

  cf:
    icon: ability_racial_twoforms
    body: |-
      /cancelform

  flap:
    body: |-
      #showtooltip Moonkin Form
      /cast [noform:4] Moonkin Form
      /cast [form:4] Flap

  wch:
    body: |-
      #showtooltip Wild Charge
      /cancelform
      /cast [@anyfriend] Wild Charge

  src:
    body: |-
      #showtooltip
      /cast [@player] Remove Corruption

  motw:
    body: |-
      #showtooltip
      /cast [@player] Mark of the Wild

  slb:
    body: |-
      #showtooltip
      /cast [@player] Lifebloom

  swg:
    body: |-
      #showtooltip
      /cast [@player] Wild Growth

  ssm:
    body: |-
      #showtooltip
      /cast [@player] Swiftmend

  sog:
    body: |-
      #showtooltip
      /cast [@player] Overgrowth

  srg:
    body: |-
      #showtoolip
      /cast [@player] Regrowth

  scw:
    body: |-
      #showtooltip
      /cast [@player] Cenarion Ward

  sib:
    body: |-
      #showtooltip
      /cast [@player] Ironbark

  sngg:
    body: |-
      #showtooltip
      /cast [@player,known:Nourish] Nourish; [@player] Grove Guardians

  suv:
    body: |-
      #showtooltip
      /cast [@player] Ursol's Vortex

  seff:
    body: |-
      #showtooltip
      /cast [@player] Efflorescence

  sal:
    body: |-
      #showtooltip
      /cast [@player] Ancient of Lore

  sinv:
    body: |-
      #showtooltip
      /cast [@player] Innervate

  srj:
    body: |-
      #showtooltip
      /cast [@player] Rejuvenation

  sig:
    body: |-
      #showtooltip
      /cast [@player] Invigorate

  root:
    body: |-
      #showtooltip
      /cast [known:Mass Entanglement] Mass Entanglement; Ursol's Vortex

  ngg:
    body: |-
      #showtooltip
      /cast [known:Nourish] Nourish; Grove Guardians

  ult:
    body: |-
      #showtooltip
      /cast [known:Convoke the Spirits] Convoke the Spirits; Incarnation: Tree of Life

  ffsb:
    body: |-
      #showtooltip
      /cast Skull Bash
      /changeactionbar 1
