---
# 11
by_name:
  trav:
    body: |-
      #showtooltip
      /cast [indoors] !Cat Form; !Travel Form

  prow:
    body: |-
      #showtooltip Prowl
      /cast [nocombat] !Prowl
      /changeactionbar 1

  cat:
    body: |-
      #showtooltip Cat Form
      /cast [noform:2] Cat Form
      /changeactionbar 1

  bear:
    body: |-
      #showtooltip Bear Form
      /cast [noform:1] Bear Form
      /changeactionbar 1

  beam:
    body: |-
      #showtooltip
      /cast Solar Beam
      /cast Mass Entanglement

  cf:
    icon: ability_racial_twoforms
    body: |-
      /cancelform

  flap:
    body: |-
      #showtooltip Moonkin Form
      /cast [noform:4] Moonkin Form
      /cast [form:4] Flap

  wch:
    body: |-
      #showtooltip Wild Charge
      /cancelform
      /cast [@anyfriend] Wild Charge

  src:
    body: |-
      #showtooltip
      /cast [@player] Remove Corruption

  motw:
    body: |-
      #showtooltip
      /cast [@player] Mark of the Wild

  slb:
    body: |-
      #showtooltip
      /cast [@player] Lifebloom

  swg:
    body: |-
      #showtooltip
      /cast [@player] Wild Growth

  ssm:
    body: |-
      #showtooltip
      /cast [@player] Swiftmend

  srg:
    body: |-
      #showtoolip
      /cast [@player] Regrowth

  sib:
    body: |-
      #showtooltip
      /cast [@player] Ironbark

  suv:
    body: |-
      #showtooltip
      /cast [@player] Ursol's Vortex

  seff:
    body: |-
      #showtooltip
      /cast [@player] Efflorescence

  sinv:
    body: |-
      #showtooltip
      /cast [@player] Innervate

  srj:
    body: |-
      #showtooltip
      /cast [@player] Rejuvenation

  root:
    body: |-
      #showtooltip
      /cast [known:Mass Entanglement] Mass Entanglement; Ursol's Vortex

  ult:
    body: |-
      #showtooltip
      /cast [known:Convoke the Spirits] Convoke the Spirits; Incarnation: Tree of Life

  ffsb:
    body: |-
      #showtooltip
      /cast Skull Bash
      /changeactionbar 1

  bvoke:
    body: |-
      #showtooltip Convoke the Spirits
      /cast Berserking
      /cast Convoke the Spirits

  ffr:
    # icon: ability_druid_disembowel
    body: |-
      #showtooltip
      /cast Rake
      /changeactionbar 1
  ffm:
    # icon: ability_druid_mangle2
    body: |-
      #showtooltip
      /cast Mangle
      /changeactionbar 1
  ffs:
    # icon: spell_shadow_vampiricaura
    body: |-
      #showtooltip
      /cast Shred
      /changeactionbar 1

  dirmb:
    body: |-
      #showtooltip
      /cast [known:Mighty Bash] Mighty Bash; Incapacitating Roar

  dfnwe:
    body: |-
      #showtooltip
      /cast [known:Force of Nature] Force of Nature; Warrior of Elune
