---
# 13
array:
  - name: self
    body: |-
      #showtooltip
      /cast [@player] Living Flame

  - name: harm
    body: |-
      #showtooltip Living Flame
      /targetenemy [help]
      /cast [harm] Living Flame
      /cleartarget

  - name: help
    body: |-
      #showtooltip Living Flame
      /targetfriend [harm]
      /cast [help] Living Flame
      /cleartarget
