---
# 13
by_name:
  slf:
    body: |-
      #showtooltip
      /cast [@player] Living Flame

  elf:
    body: |-
      #showtooltip
      /cast [@anyenemy] Living Flame

  flf:
    body: |-
      #showtooltip
      /cast [@anyfriend] Living Flame

  scf:
    body: |-
      #showtooltip
      /cast [@player] Cauterizing Flame

  std:
    body: |-
      #showtooltip
      /cast [@player] Time Dilation

  ssb:
    body: |-
      #showtooltip
      /cast [@player] Spiritbloom

  sn:
    body: |-
      #showtooltip
      /cast [@player] Naturalize

  seb:
    body: |-
      #showtooltip
      /cast [@player] Emerald Blossom

  sve:
    body: |-
      #showtooltip
      /cast [@player] Verdant Embrace

  sr:
    body: |-
      #showtooltip
      /cast [@player] Reversion

  se:
    body: |-
      #showtooltip
      /cast [@player] Echo

  sx:
    body: |-
      #showtooltip
      /cast [@player] Expunge

  sts:
    body: |-
      #showtooltip
      /cast [@player] Time Stop
