---
# 3
by_name:
  bssc:
    body: |-
      #showtooltip
      /cast [known:Bursting Shot] Bursting Shot; Scatter Shot

  heti:
    body: |-
      #showtooltip
      /cast [known:High Explosive Trap] High Explosive Trap; Implosive Trap

  bfs:
    body: |-
      #showtooltip
      /cast [known:Butchery] Butchery; Flanking Strike

  sf:
    body: |-
      #showtooltip
      /cast [@player] Flare

  scp:
    body: |-
      #showtooltip
      /cast [@player] Command Pet

  sfp:
    body: |-
      #showtooltip
      /cast [@player] Flamefang Pitch

  cp:
    body: |-
      #showtooltip
      /cast Command Pet

  stt:
    body: |-
      #showtooltip
      /cast [@player,known:Tar Trap] Tar Trap; Scare Beast

  ttsb:
    body: |-
      #showtooltip
      /cast [known:Tar Trap] Tar Trap; Scare Beast

  sros:
    body: |-
      #showtooltip
      /cast [@player] Roar of Sacrifice

  sft:
    body: |-
      #showtooltip
      /cast [@player] Freezing Trap

  sbs:
    body: |-
      #showtooltip
      /cast [@player] Binding Shot

  shet:
    body: |-
      #showtooltip
      /cast [@player] High Explosive Trap

  smb:
    body: |-
      #showtooltip
      /cast [@player] Mending Bandage

  sdbh:
    body: |-
      #showtooltip
      /cast [@player] Dire Beast: Hawk

  sv:
    body: |-
      #showtooltip
      /cast [@player] Volley

  ks:
    body: |-
      #showtooltip Kill Shot
      /cast Blood Fury
      /cast Kill Shot

  tdr:
    body: |-
      #showtooltip Takedown
      /cast Blood Fury
      /cast Takedown

  brr:
    body: |-
      #showtooltip Bestial Wrath
      /cast Blood Fury
      /cast Bestial Wrath
