---
# 3
by_name:
  bssc:
    body: |-
      #showtooltip
      /cast [known:Bursting Shot] Bursting Shot; Scatter Shot

  heti:
    body: |-
      #showtooltip
      /cast [known:High Explosive Trap] High Explosive Trap; Implosive Trap

  bfs:
    body: |-
      #showtooltip
      /cast [known:Butchery] Butchery; Flanking Strike

  sf:
    body: |-
      #showtooltip
      /cast [@player] Flare

  scp:
    body: |-
      #showtooltip
      /cast [@player] Command Pet

  cp:
    body: |-
      #showtooltip
      /cast Command Pet

  stt:
    body: |-
      #showtooltip
      /cast [@player] Tar Trap

  sros:
    body: |-
      #showtooltip
      /cast [@player] Roar of Sacrifice

  sft:
    body: |-
      #showtooltip
      /cast [@player] Freezing Trap

  sbs:
    body: |-
      #showtooltip
      /cast [@player] Binding Shot

  shet:
    body: |-
      #showtooltip
      /cast [@player] High Explosive Trap

  smb:
    body: |-
      #showtooltip
      /cast [@player] Mending Bandage

  sdbh:
    body: |-
      #showtooltip
      /cast [@player] Dire Beast: Hawk

  sv:
    body: |-
      #showtooltip
      /cast [@player] Volley

  ks:
    body: |-
      #showtooltip
      /cast Kill Shot
