---
# 8
by_name:
  sai:
    body: |-
      #showtooltip
      /cast [@player] Arcane Intellect

  src:
    body: |-
      #showtooltip
      /cast [@player] Remove Curse

  sfs:
    body: |-
      #showtooltip
      /cast [@player] Flamestrike

  ssf:
    body: |-
      #showtooltip
      /cast [@player] Slow Fall

  sb:
    body: |-
      #showtooltip
      /cast [@player] Blizzard

  srof:
    body: |-
      #showtooltip
      /cast [@player] Ring of Frost

  cat:
    icon: spell_mage_altertime_active
    body: |-
      /cancelaura Alter Time

  ibc:
    body: |-
      #showtooltip Ice Block
      /cancelaura Ice Block
      /cast Ice Block
