---
# 10
by_name:
  rop:
    body: |-
      #showtooltip
      /cast [known:Ring of Peace] Ring of Peace; Song of Chi-Ji

  srop:
    body: |-
      #showtooltip
      /cast [@player,known:Ring of Peace] Ring of Peace; Song of Chi-Ji

  stl:
    body: |-
      #showtooltip
      /cast [@player] Tiger's Lust

  sd:
    body: |-
      #showtooltip
      /cast [@player] Detox

  sv:
    body: |-
      #showtooltip
      /cast [@player] Vivify

  ssm:
    body: |-
      #showtooltip
      /cast [@player] Soothing Mist

  szs:
    body: |-
      #showtooltip
      /cast [@player] Zen Spheres

  ezs:
    body: |-
      #showtooltip
      /cast [@anyenemy] Zen Spheres

  fzs:
    body: |-
      #showtooltip
      /cast [@anyfriend] Zen Spheres

  sem:
    body: |-
      #showtooltip
      /cast [@player] Enveloping Mist

  srm:
    body: |-
      #showtooltip
      /cast [@player] Renewing Mist

  sjss:
    body: |-
      #showtooltip
      /cast [@player] Summon Jade Serpent Statue

  shs:
    body: |-
      #showtooltip
      /cast [@player] Healing Sphere

  slc:
    body: |-
      #showtooltip
      /cast [@player] Life Cocoon

  ssg:
    body: |-
      #showtooltip
      /cast [@player] Sheilun's Gift

  rev:
    body: |-
      #showtooltip
      /cast [known:Revival] Revival; Restoral
