---
# 10
by_name:
  rop:
    body: |-
      #showtooltip
      /cast [known:Ring of Peace] Ring of Peace; Song of Chi-Ji

  srop:
    body: |-
      #showtooltip
      /cast [@player,known:Ring of Peace] Ring of Peace; Song of Chi-Ji

  stl:
    body: |-
      #showtooltip
      /cast [@player] Tiger's Lust

  sd:
    body: |-
      #showtooltip
      /cast [@player] Detox

  sv:
    body: |-
      #showtooltip
      /cast [@player] Vivify

  ssm:
    body: |-
      #showtooltip
      /cast [@player] Soothing Mist

  sem:
    body: |-
      #showtooltip
      /cast [@player] Enveloping Mist

  srm:
    body: |-
      #showtooltip
      /cast [@player] Renewing Mist

  sjss:
    body: |-
      #showtooltip
      /cast [@player] Summon Jade Serpent Statue

  slc:
    body: |-
      #showtooltip
      /cast [@player] Life Cocoon

  rev:
    body: |-
      #showtooltip
      /cast [known:Revival] Revival; Restoral

  swwdp:
    body: |-
      #showtooltip
      /cast [known:Strike of the Windlord] Strike of the Windlord; Whirling Dragon Punch
