---
# 2
by_name:
  sfr:
    body: |-
      #showtooltip
      /cast [@player] Final Reckoning

  sbop:
    body: |-
      #showtooltip
      /cast [@player] Blessing of Protection

  swog:
    body: |-
      #showtooltip
      /cast [@player] Word of Glory

  sloh:
    body: |-
      #showtooltip
      /cast [@player] Lay on Hands

  sfol:
    body: |-
      #showtooltip
      /cast [@player] Flash of Light

  sbos:
    body: |-
      #showtooltip
      /cast [@player] Blessing of Sanctuary

  sbow:
    body: |-
      #showtooltip
      /cast [@player] Blessing of Spellwarding

  sbof:
    body: |-
      #showtooltip
      /cast [@player] Blessing of Freedom

  sct:
    body: |-
      #showtooltip
      /cast [@player] Cleanse Toxins

  rbl:
    body: |-
      #showtooltip
      /cast [known:Blinding Light] Blinding Light; Repentance

  esfr:
    body: |-
      #showtooltip
      /cast [known:Final Reckoning] Final Reckoning; Execution Sentence

  shs:
    body: |-
      #showtooltip
      /cast [@player] Holy Shock

  ehs:
    body: |-
      #showtooltip
      /cast [@anyenemy] Holy Shock

  fhs:
    body: |-
      #showtooltip
      /cast [@anyfriend] Holy Shock

  shp:
    body: |-
      #showtooltip
      /cast [@player] Holy Prism

  ehp:
    body: |-
      #showtooltip
      /cast [@anyenemy] Holy Prism

  fhp:
    body: |-
      #showtooltip
      /cast [@anyfriend] Holy Prism

  shl:
    body: |-
      #showtooltip
      /cast [@player] Holy Light

  sbol:
    body: |-
      #showtooltip
      /cast [@player] Beacon of Light

  sc:
    body: |-
      #showtooltip
      /cast [@player] Cleanse

  sboi:
    body: |-
      #showtooltip
      /cast [@player] Barrier of Faith

  sbom:
    body: |-
      #showtooltip
      /cast [@player] Blessing of Summer

  shb:
    body: |-
      #showtooltip
      /cast [@player] Holy Bulwark

  wa14:
    body: |-
      #showtooltip Wake of Ashes
      /use 14
      /cast Wake of Ashes
