---
# 2
by_name:
  sfr:
    body: |-
      #showtooltip
      /cast [@player] Final Reckoning

  sbop:
    body: |-
      #showtooltip
      /cast [@player] Blessing of Protection

  swog:
    body: |-
      #showtooltip
      /cast [@player] Word of Glory

  sloh:
    body: |-
      #showtooltip
      /cast [@player] Lay on Hands

  sfol:
    body: |-
      #showtooltip
      /cast [@player] Flash of Light

  sbos:
    body: |-
      #showtooltip
      /cast [@player] Blessing of Sanctuary

  sbow:
    body: |-
      #showtooltip
      /cast [@player] Blessing of Spellwarding

  sbof:
    body: |-
      #showtooltip
      /cast [@player] Blessing of Freedom

  sct:
    body: |-
      #showtooltip
      /cast [@player] Cleanse Toxins

  esfr:
    body: |-
      #showtooltip
      /cast [known:Final Reckoning] Final Reckoning; Execution Sentence

  dthp:
    body: |-
      #showtooltip
      /cast [@anyfriend,known:Divine Toll] Divine Toll; [@anyfriend] Holy Prism
  sdthp:
    body: |-
      #showtooltip
      /cast [@player,known:Divine Toll] Divine Toll; [@player] Holy Prism
  edthp:
    body: |-
      #showtooltip
      /cast [@anyenemy,known:Divine Toll] Divine Toll; [@anyenemy] Holy Prism

  shs:
    body: |-
      #showtooltip
      /cast [@player] Holy Shock

  ehs:
    body: |-
      #showtooltip
      /cast [@anyenemy] Holy Shock

  fhs:
    body: |-
      #showtooltip
      /cast [@anyfriend] Holy Shock

  shl:
    body: |-
      #showtooltip
      /cast [@player] Holy Light

  sbol:
    body: |-
      #showtooltip
      /cast [@player] Beacon of Light

  sc:
    body: |-
      #showtooltip
      /cast [@player] Cleanse

  shb:
    body: |-
      #showtooltip
      /cast [@player] Holy Bulwark

  wa14:
    body: |-
      #showtooltip Wake of Ashes
      /use 14
      /cast Wake of Ashes
