---
# 5
by_name:
  mcdm:
    body: |-
      #showtooltip
      /cast [known:Mind Control] Mind Control; Dominate Mind

  lbpb:
    body: |-
      #showtooltip
      /cast [known:Luminous Barrier] Luminous Barrier; Power Word: Barrier

  spwf:
    body: |-
      #showtooltip
      /cast [@player] Power Word: Fortitude

  saf:
    body: |-
      #showtooltip
      /cast [@player] Angelic Feather

  sl:
    body: |-
      #showtooltip
      /cast [@player] Levitate

  sp:
    body: |-
      #showtooltip
      /cast [@player] Purify

  smd:
    body: |-
      #showtooltip
      /cast [@player] Mass Dispel

  spwl:
    body: |-
      #showtooltip
      /cast [@player] Power Word: Life

  sr:
    body: |-
      #showtooltip
      /cast [@player] Renew

  spom:
    body: |-
      #showtooltip
      /cast [@player] Prayer of Mending

  shws:
    body: |-
      #showtooltip
      /cast [@player] Holy Word: Serenity

  shwy:
    body: |-
      #showtooltip
      /cast [@player] Holy Word: Sanctify

  sgs:
    body: |-
      #showtooltip
      /cast [@player] Guardian Spirit

  spws:
    body: |-
      #showtooltip
      /cast [@player] Power Word: Shield

  sfh:
    body: |-
      #showtooltip
      /cast [@player] Flash Heal

  splea:
    body: |-
      #showtooltip
      /cast [@player] Plea

  spoh:
    body: |-
      #showtooltip
      /cast [@player] Prayer of Healing

  sn:
    body: |-
      #showtooltip
      /cast [@player] Penance

  en:
    body: |-
      #showtooltip
      /cast [@anyenemy] Penance

  fn:
    body: |-
      #showtooltip
      /cast [@anyfriend] Penance

  fnd:
    body: |-
      #showtooltip
      /cast [@anyenemy] Shadowfiend

  spwr:
    body: |-
      #showtooltip
      /cast [@player] Power Word: Radiance

  sps:
    body: |-
      #showtooltip
      /cast [@player] Pain Suppression

  spwb:
    body: |-
      #showtooltip
      /cast [@player] Power Word: Barrier

  eup:
    body: |-
      #showtooltip
      /cast [@anyenemy] Ultimate Penitence

  fup:
    body: |-
      #showtooltip
      /cast [@anyfriend] Ultimate Penitence
