---
# 5
array:
  - name: harm
    body: |-
      #showtooltip
      /cast [@anyenemy] Ultimate Penitence

  - name: harm
    body: |-
      #showtooltip
      /cast [@anyenemy] Penance

  - name: harm
    body: |-
      #showtooltip
      /cast [@anyenemy] Shadowfiend

  - name: help
    body: |-
      #showtooltip
      /cast [@anyfriend] Penance

  - name: help
    body: |-
      #showtooltip
      /cast [@anyfriend] Ultimate Penitence

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Purify

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Penance

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Shadow Crash

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Mass Dispel

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Power Word: Barrier

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Power Word: Shield

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Flash Heal

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Renew

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Pain Suppression

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Power Word: Life

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Power Word: Fortitude

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Power Word: Radiance

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Angelic Feather

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Levitate

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Rapture

  - name: form
    body: |-
      #showtooltip
      /cast !Shadowform
