---
# 4
by_name:
  a1:
    body: |-
      #showtooltip Shadowstep
      /cast [@arena1] Shadowstep
      /cast [@arena1] Kick

  a2:
    body: |-
      #showtooltip Shadowstep
      /cast [@arena2] Shadowstep
      /cast [@arena2] Kick

  a3:
    body: |-
      #showtooltip Shadowstep
      /cast [@arena3] Shadowstep
      /cast [@arena3] Kick

  s:
    body: |-
      #showtooltip Stealth
      /cancelaura [nocombat] Shadow Dance
      /stopattack
      /cast !Stealth

  ssap:
    body: |-
      #showtooltip Sap
      /cleartarget
      /targetenemyplayer
      /cast Sap
      /stopattack

  ess:
    body: |-
      #showtooltip
      /cast [@anyenemy] Shadowstep

  fss:
    body: |-
      #showtooltip
      /cast [@anyfriend] Shadowstep

  ksbf:
    body: |-
      #showtooltip Killing Spree
      /cast Blood Fury
      /cast Killing Spree

  dmbf:
    body: |-
      #showtooltip Deathmark
      /cast Blood Fury
      /cast Deathmark

  stec:
    body: |-
      #showtooltip Secret Technique
      /use 14
      /cast Blood Fury
      /cast Secret Technique

  np:
    body: |-
      #showtooltip
      /cast [known:Numbing Poison] Numbing Poison; Atrophic Poison
