---
# 4
array:
  - name: 1
    body: |-
      #showtooltip Shadowstep
      /cast [@arena1] Shadowstep
      /cast [@arena1] Kick

  - name: 2
    body: |-
      #showtooltip Shadowstep
      /cast [@arena2] Shadowstep
      /cast [@arena2] Kick

  - name: 3
    body: |-
      #showtooltip Shadowstep
      /cast [@arena3] Shadowstep
      /cast [@arena3] Kick

  - name: s
    body: |-
      #showtooltip Stealth
      /cancelaura [nocombat] Shadow Dance
      /stopattack
      /cast !Stealth

  - name: ssap
    body: |-
      #showtooltip Sap
      /cleartarget
      /targetenemyplayer
      /cast Sap
      /stopattack
