---
# 7
array:
  - name: self
    body: |-
      #showtooltip
      /cast [@player] Water Walking

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Skyfury

  - name: self
    body: |-
      #showtooltip
      /cast [@player] Healing Surge
