---
GamePadEnable: 1
GamePadEmulateAlt: "PADPADDLE2"
GamePadEmulateShift: "PADLSHOULDER"
GamePadEmulateCtrl: "PADLTRIGGER"
GamePadRunThreshold: 0
GamePadCameraYawSpeed: 1.75
GamePadOverlapMouseMs: 50

# 0 == camera centered placement, 1 == regular mouse, 2 == mouse snap to target
GamePadCursorForTargeting: 2
GamePadCursorAutoDisableSticks: 1

AutoPushSpellToActionBar: 0
advancedCombatLogging: 1
autoLootDefault: 1
autoLootRate: 50
enableMultiActionBars: 15
SoftTargetEnemy: 3
SoftTargetFriend: 3
SoftTargetInteract: 3
SoftTargetIconFriend: 1
SoftTargetNameplateInteract: 1

scriptErrors: 1
scriptWarnings: 1

floatingCombatTextCombatDamage: 0
floatingCombatTextCombatHealing: 0

cameraSmoothStyle: 1
countdownForCooldowns: 1

hideAdventureJournalAlerts: 1
showTutorials: 0

spellBookHidePassives: 1

pvpFramesDisplayClassColor: 1
pvpFramesDisplayPowerBars: 1
raidFramesDisplayClassColor: 1
raidFramesDisplayPowerBars: 1

# Coerce some defaults too (is there a 'reset to default' mechanism in LUA?).
# /console cvar_default
SoftTargetIconEnemy: 0

NameplatePersonalShowAlways: 1
nameplateSelfTopInset: 0.45
nameplateSelfBottomInset: 0.45
nameplateSelfScale: 1.0

# Overwritten by role-based logic.
# nameplateShowFriends: 1
# nameplateShowEnemies: 1

# Overwritten by content-based logic.
# UnitNameFriendlyPlayerName: 0
# UnitNameEnemyPlayerName: 0

nameplateShowSelf: 1
nameplateShowDebuffsOnFriendly: 1  # default
nameplateHideHealthAndPower: 1

occludedSilhouettePlayer: 1

combinedBags: 1

lossOfControl: 0

UnitNamePlayerPVPTitle: 0
UnitNamePlayerGuild: 0
UnitNameOwn: 0
UnitNameNPC: 0
UnitNameInteractiveNPC: 1  # default

pvpFramesHealthText: "none"
raidFramesHealthText: "none"

showToastWindow: 0

Sound_EnableSFX: 1  # default
Sound_EnableMusic: 0
Sound_EnableAmbience: 0
Sound_EnableDialog: 0
Sound_EnableSoundWhenGameIsInBG: 1
Sound_MasterVolume: 1
Sound_SFXVolume: 1
Sound_EnableReverb: 1  # default
Sound_EnableEmoteSounds: 0

# BetterBlizzPlates does all of these
# Gets overwritten by "use large nameplates" ?
# nameplateSelfScale: 1.0
# nameplateGlobalScale: 1
# nameplateLargerScale: 1.2
# NamePlateHorizontalScale: 0.5
# NamePlateVerticalScale: 1
# nameplateSelectedScale: 1.2
# nameplateMinScale: 0.9
# nameplateMaxScale: 0.9

showPartyPets: 1
raidOptionDisplayPets: 1

nameplateShowFriendlyBuffs: 1
nameplateShowFriendlyTotems: 1
nameplateShowPersonalCooldowns: 1

SoftTargetNameplateFriend: 0

nameplateMotion: 1
nameplateMotionSpeed: 0.05
nameplateOverlapH: 0.6
nameplateOverlapV: 0.6
