---
GamePadEnable: 1
GamePadEmulateAlt: "PADPADDLE2"
GamePadEmulateShift: "PADLSHOULDER"
GamePadEmulateCtrl: "PADLTRIGGER"
GamePadRunThreshold: 0
GamePadCameraYawSpeed: 1.75
AutoPushSpellToActionBar: 0
advancedCombatLogging: 1
autoLootDefault: 1
autoLootRate: 50
enableMultiActionBars: 15
SoftTargetEnemy: 3
SoftTargetFriend: 3
SoftTargetInteract: 3
SoftTargetIconFriend: 1
SoftTargetNameplateInteract: 1

floatingCombatTextCombatDamage: 0
floatingCombatTextCombatHealing: 0

cameraSmoothStyle: 1

hideAdventureJournalAlerts: 1

spellBookHidePassives: 1

pvpFramesDisplayClassColor: 1
raidFramesDisplayClassColor: 1

# Coerce some defaults too (is there a 'reset to default' mechanism in LUA?).
# /console cvar_default
SoftTargetIconEnemy: 0
