---
GamePadEnable: 1
GamePadEmulateAlt: "PADPADDLE2"
GamePadEmulateShift: "PADLSHOULDER"
GamePadEmulateCtrl: "PADLTRIGGER"
GamePadRunThreshold: 0
GamePadCameraYawSpeed: 3.0
GamePadCameraPitchSpeed: 2.0
GamePadOverlapMouseMs: 50

# 0 == camera centered placement, 1 == regular mouse, 2 == mouse snap to target
GamePadCursorForTargeting: 0
GamePadCursorAutoDisableSticks: 1
GamePadCursorSpeedMax: 2
GamePadCursorSpeedStart: 0.5

ActionButtonUseKeyHeldSpell: 1

AutoPushSpellToActionBar: 0
advancedCombatLogging: 1
autoLootDefault: 1
autoLootRate: 50
enableMultiActionBars: 15
SoftTargetEnemy: 3
SoftTargetFriend: 3
SoftTargetInteract: 3
SoftTargetIconFriend: 1
SoftTargetNameplateInteract: 1

scriptErrors: 1

statusText: 0
statusTextDisplay: NONE

threatWorldText: 0

cameraSmoothStyle: 1
countdownForCooldowns: 1

showTutorials: 0
showHonorAsExperience: 0

spellBookHidePassives: 1

pvpFramesDisplayClassColor: 1
pvpFramesDisplayPowerBars: 1
raidFramesDisplayClassColor: 1
raidFramesDisplayPowerBars: 1

# Coerce some defaults too (is there a 'reset to default' mechanism in LUA?).
# /console cvar_default
SoftTargetIconEnemy: 0

nameplateSelfAlpha: 0.75

# Overwritten by role-based logic.
# nameplateShowFriends: 1
# nameplateShowEnemies: 1

# Overwritten by content-based logic.
# UnitNameFriendlyPlayerName: 0
# UnitNameEnemyPlayerName: 0

nameplateShowSelf: 0  # useless without BetterBlizzPlates aura bar
nameplateShowAll: 1
nameplateShowDebuffsOnFriendly: 1  # default

occludedSilhouettePlayer: 1

combinedBags: 1

lossOfControl: 0

UnitNamePlayerPVPTitle: 0
UnitNamePlayerGuild: 0
UnitNameOwn: 0
UnitNameNPC: 0
UnitNameInteractiveNPC: 1  # default

pvpFramesHealthText: "none"
raidFramesHealthText: "none"

showToastWindow: 0

Sound_EnableSFX: 1  # default
Sound_EnableMusic: 0
Sound_EnableAmbience: 1
Sound_EnableDialog: 0
Sound_EnableSoundWhenGameIsInBG: 1  # for queue pop
Sound_MasterVolume: 1
Sound_SFXVolume: 1
Sound_EnableReverb: 1  # default
Sound_EnableEmoteSounds: 0

# feature only used for griefing
enablePings: 0
showPingsInChat: 0
Sound_EnablePingSounds: 0

# BetterBlizzPlates does all of these
# Gets overwritten by "use large nameplates" ?
# nameplateSelfScale: 1.0
nameplateLargerScale: 1.2
# NamePlateHorizontalScale: 0.5
# NamePlateVerticalScale: 1
# nameplateSelectedScale: 1.2

nameplateMinScale: 0.9
nameplateMaxScale: 0.9

showPartyPets: 1
raidOptionDisplayPets: 1

nameplateShowFriendlyPlayerTotems: 0

SoftTargetNameplateFriend: 0

nameplateOverlapH: 0.6
nameplateOverlapV: 0.6

cooldownViewerEnabled: 1
assistedCombatHighlight: 1

# 'basic' https://wowpedia.fandom.com/wiki/CVar_ActionCam
test_cameraDynamicPitch: 1
test_cameraHeadMovementStrength: 0
test_cameraOverShoulder: 0
test_cameraTargetFocusInteractEnable: 0
test_cameraTargetFocusEnemyEnable: 0
CameraKeepCharacterCentered: 0

cameraDistanceMaxZoomFactor: 2.6
cameraFov: 90

rotateMinimap: 0

ReplaceMyPlayerPortrait: 1
ReplaceOtherPlayerPortraits: 1

noBuffDebuffFilterOnTarget: 1

# midnight stuff
damageMeterEnabled: 0  # not many features yet, off by default
externalDefensivesEnabled: 1
lootUnderMouse: 0
showTargetOfTarget: 1
spellDiminishPVPOnlyTriggerableByMe: 1
secretPvPMatchRestrictionsForced: 1
nameplateSize: 5
nameplateStyle: 4
nameplateAuraScale: 0.7
pvpFramesDisplayOnlyHealerPowerBars: 1
raidFramesDisplayOnlyHealerPowerBars: 1
pvpOptionDisplayPets: 1
nameplateShowOffscreen: 1

synchronizeConfig: 0

# graphics
RAIDsettingsEnabled: 0
# graphicsViewDistance: 0
graphicsSpellDensity: 2
graphicsProjectedTextures: 1
useTargetFPS: 0
useMaxFPS: 0
useMaxFPSBk: 1
maxFPSBk: 30

# graveyard
# nameplateShowFriendlyBuffs: 1
# nameplateSelfScale: 1.0
# hideAdventureJournalAlerts: 1
# NameplatePersonalShowAlways: 1
# nameplateOtherTopInset: 0.08
# nameplateSelfBottomInset: 0.31
# nameplateOtherBottomInset: 0.1
# nameplateSelfTopInset: 0.50
# nameplateLargeTopInset: 0.1
# nameplateResourceOnTarget: 0
# nameplateShowPersonalCooldowns: 1
# nameplateHideHealthAndPower: 1
# nameplateMotionSpeed: 0.05
# nameplateMotion: 1
# nameplateGlobalScale: 1.0
# floatingCombatTextCombatDamage: 0
# floatingCombatTextCombatHealing: 0
# floatingCombatTextCombatState: 0
# floatingCombatTextSpellMechanics: 0
# floatingCombatTextPetMeleeDamage: 0
# floatingCombatTextPetSpellDamage: 0
# floatingCombatTextReactives: 0
# WorldTextScale: 0
