---
GamePadEnable: 1
GamePadEmulateAlt: "PADPADDLE2"
GamePadEmulateShift: "PADLSHOULDER"
GamePadEmulateCtrl: "PADLTRIGGER"
GamePadRunThreshold: 0
GamePadCameraYawSpeed: 1.75
AutoPushSpellToActionBar: 0
advancedCombatLogging: 1
autoLootDefault: 1
autoLootRate: 50
enableMultiActionBars: 15
SoftTargetEnemy: 3
SoftTargetFriend: 3
SoftTargetInteract: 3
SoftTargetIconFriend: 1
SoftTargetNameplateInteract: 1

floatingCombatTextCombatDamage: 0
floatingCombatTextCombatHealing: 0

cameraSmoothStyle: 1
countdownForCooldowns: 1

hideAdventureJournalAlerts: 1
showTutorials: 0

spellBookHidePassives: 1

pvpFramesDisplayClassColor: 1
pvpFramesDisplayPowerBars: 1
raidFramesDisplayClassColor: 1
raidFramesDisplayPowerBars: 1

# Coerce some defaults too (is there a 'reset to default' mechanism in LUA?).
# /console cvar_default
SoftTargetIconEnemy: 0

NameplatePersonalShowAlways: 1
nameplateSelfTopInset: 0.45
nameplateSelfBottomInset: 0.45
nameplateSelfScale: 1.0

nameplateShowFriends: 1
nameplateShowSelf: 1
nameplateShowEnemies: 1
nameplateShowDebuffsOnFriendly: 1  # default

# nameplateSelfScale: 1.0
# nameplateGlobalScale: 1
# nameplateLargerScale: 1.2

# Some variables can't be set..
# nameplateShowFriendlyBuffs: 1
# nameplateShowFriendlyTotems: 1
