---
PADRTRIGGER: BUTTON4
PADRSHOULDER: BUTTON5
PAD1: S
PAD2: R
PAD3: Q
PAD4: 3

PADDLEFT: 2
PADDUP: MOUSEWHEELUP
PADDDOWN: MOUSEWHEELDOWN
PADDRIGHT: 4

PADLSTICK: T
PADRSTICK: V

PADBACK: Z
PADSYSTEM: X
PADFORWARD: C

PADPADDLE1: SPACE
PADPADDLE2: ALT
PADPADDLE3: F
PADPADDLE4: 1
