---
by_name:
  t13:
    body: |-
      #showtooltip
      /use 13

  t14:
    body: |-
      #showtooltip
      /use 14

  gc:
    icon: creatureportrait_creature_iceblock
    body: |-
      /stopcasting
      /cancelaura Slow Fall
      /cancelaura Levitate
      /cancelaura Enchanted Candle
      /cancelaura Alter Time

  dis:
    icon: ability_marksmanship
    body: |-
      /dismount
      /cancelform

  gak:
    icon: inv_misc_enggizmos_swissarmy
    body: |-
      /gnomish-army-knife

  gg:
    icon: achievement_bg_takexflags_ab
    body: |-
      /run LeaveBattlefield()

  hs:
    body: |-
      #showtooltip
      /use Healthstone

  mana:
    icon: inv_drink_milk_01
    body: |-
      /cleartarget
      /use Conjured Mana Bun
      /use Quicksilver Sipper

  petd:
    icon: inv_leatherworking_70_petleash
    body: |-
      /petdismiss

  ffr:
    # icon: ability_druid_disembowel
    body: |-
      #showtooltip
      /cast Rake
      /changeactionbar 1

  ffm:
    # icon: ability_druid_mangle2
    body: |-
      #showtooltip
      /cast Mangle
      /changeactionbar 1

  ffs:
    # icon: spell_shadow_vampiricaura
    body: |-
      #showtooltip
      /cast Shred
      /changeactionbar 1

  fav:
    icon: achievement_guildperk_mountup
    body: |-
      /run C_MountJournal.SummonByID(0)

  yak:
    icon: ability_mount_travellersyakmount
    body: |-
      /use Grand Expedition Yak

  ah:
    icon: inv_brontsaurusmountspecial
    body: |-
      /use Trader's Gilded Brutosaur

  dfnwe:
    body: |-
      #showtooltip
      /cast [known:Force of Nature] Force of Nature; Warrior of Elune

  dirmb:
    body: |-
      #showtooltip
      /cast [known:Mighty Bash] Mighty Bash; Incapacitating Roar

  psf:
    body: |-
      #showtooltip
      /cast !Shadowform

  pdave:
    body: |-
      #showtooltip
      /cast [known:Dark Ascension] Dark Ascension; Void Eruption

  bvoke:
    body: |-
      #showtooltip Convoke the Spirits
      /cast Berserking
      /cast Convoke the Spirits

  pssc:
    body: |-
      #showtooltip
      /cast [@player] Shadow Crash

  ppd:
    body: |-
      #showtooltip
      /cast [@player] Purify Disease
