---
array:
  - name: "13"
    body: |-
      #showtooltip
      /use 13

  - name: "14"
    body: |-
      #showtooltip
      /use 14

  - name: canc
    icon: creatureportrait_creature_iceblock
    body: |-
      /stopcasting
      /cancelaura Slow Fall
      /cancelaura Levitate
      /cancelaura Enchanted Candle
      /cancelaura Alter Time
      /cleartarget

  - name: dis
    icon: ability_marksmanship
    body: |-
      /dismount
      /cancelform

  - name: gak
    icon: inv_misc_enggizmos_swissarmy
    body: |-
      /gnomish-army-knife

  - name: gg
    icon: achievement_bg_takexflags_ab
    body: |-
      /run LeaveBattlefield()

  - name: hs
    body: |-
      #showtooltip
      /use Healthstone

  - name: mana
    icon: inv_drink_milk_01
    body: |-
      /cleartarget
      /use Conjured Mana Bun
      /use Quicksilver Sipper

  - name: pet
    icon: inv_leatherworking_70_petleash
    body: |-
      /petdismiss

  - name: z0
    body: |-
      #showtooltip
      /cast Rake
      /changeactionbar 1

  - name: z1
    body: |-
      #showtooltip
      /cast Mangle
      /changeactionbar 1

  - name: z2
    body: |-
      #showtooltip
      /cast Skull Bash
      /changeactionbar 1
