---
# Balance Druid
by_key:
  L2_L1_R1: s "Solar Beam"
  L2_R1: s "Starfall"
  L1_R1_1: s "Sunfire"
  L1_R1_2: s "Sunfire"
  L1_R1_B: s "Swipe"
  L1_R1_C: s "Swipe"
  L1_R1_M: s "Sunfire"
  R1_1: s "Moonfire"
  R1_2: s "Moonfire"
  R1_B: s "Mangle"
  R1_C: s "Shred"
  R1_M: s "Moonfire"
  P2_R1: s "Starsurge"
  L1_P2_R1: s "Fury of Elune"

  L1_R2_1: s "Starfire"
  L1_R2_2: s "Starfire"
  L1_R2_B: s "Starfire"
  L1_R2_C: s "Starfire"
  L1_R2_M: s "Starfire"
  R2_1: s "Wrath"
  R2_2: s "Wrath"
  R2_B: s "Wrath"
  R2_C: s "Wrath"
  R2_M: s "Wrath"
  P2_R2: s "Warrior of Elune"
  L1_P2_R2: s "Mighty Bash"

  L2_S: s "Celestial Alignment"
  L1_S_C: s "Rake"
  S_C: s "Ferocious Bite"
  P2_S: m beam

  L2_X: s "Faerie Swarm"
  L1_X_1: m srj
  L1_X_2: s "Rejuvenation"
  L1_X_B: m srj
  L1_X_C: m srj
  L1_X_M: m srj
  X_1: m srg
  X_2: s "Regrowth"
  X_B: m srg
  X_C: m srg
  X_M: m srg

  L1_T_1: m src
  L1_T_2: s "Remove Corruption"
  L1_T_B: m src
  L1_T_C: m src
  L1_T_M: m src

  L1_C_B: s "Ironfur"
