---
# Feral Druid
by_key:
  L2_R1: s "Adaptive Swarm"
  L1_R1_1: s "Rake"
  L1_R1_2: s "Rake"
  L1_R1_B: s "Shred"
  L1_R1_C: s "Rake"
  L1_R1_M: s "Rake"
  R1_1: s "Shred"
  R1_2: s "Shred"
  R1_B: s "Mangle"
  R1_C: s "Shred"
  R1_M: s "Shred"
  P2_R1: s "Tiger's Fury"
  L1_P2_R1: s "Feral Frenzy"

  L1_R2_1: s "Wrath"
  L1_R2_2: s "Wrath"
  L1_R2_B: s "Ironfur"
  L1_R2_C: s "Rip"
  R2_1: s "Mangle"
  R2_2: s "Mangle"
  R2_B: s "Strength of the Wild"
  R2_C: s "Ferocious Bite"
  P2_R2: s "Maim"
  L1_P2_R2: s "Convoke the Spirits"

  L2_S: s "Berserk"
  L1_S_C: s "Primal Wrath"
  S_C: s "Swipe"

  L1_X_1: m srj
  L1_X_2: s "Rejuvenation"
  L1_X_B: m srj
  L1_X_C: m srj
  L1_X_M: m srj
  X_1: m srg
  X_2: s "Regrowth"
  X_B: m srg
  X_C: m srg
  X_M: m srg
  P2_X: s "Survival Instincts"

  L2_P2_X: s "Innervate"

  L1_T_1: m src
  L1_T_2: s "Remove Corruption"
  L1_T_B: m src
  L1_T_C: m src
  L1_T_M: m src

  T_B: s "Swipe"

  L1_C_B: s "Thrash"
  L1_C_C: s "Thrash"
