---
# Guardian Druid
by_key:
  L2_R1: ""
  L1_R1_1: ""
  L1_R1_2: ""
  L1_R1_B: ""
  L1_R1_C: ""
  L1_R1_M: ""
  R1_1: ""
  R1_2: ""
  R1_B: ""
  R1_C: ""
  R1_M: ""
  P2_R1: ""
  L1_P2_R1: ""

  L1_R2_1: ""
  L1_R2_2: ""
  L1_R2_B: ""
  L1_R2_C: ""
  L1_R2_M: ""
  R2_1: ""
  R2_2: ""
  R2_B: ""
  R2_C: ""
  R2_M: ""
  P2_R2: ""
  L1_P2_R2: ""

  L2_L1_S: ""
  L2_S: ""
  L1_S_1: ""
  L1_S_2: ""
  L1_S_C: ""
  L1_S_M: ""
  S_1: ""
  S_2: ""
  S_C: ""
  S_M: ""
  L2_P2_S: ""
  L1_P2_S: ""

  L2_X: ""
  L1_X_1: ""
  L1_X_2: ""
  L1_X_B: ""
  L1_X_C: ""
  L1_X_M: ""
  X_1: ""
  X_2: ""
  X_B: ""
  X_C: ""
  X_M: ""
  P2_X: ""
  L2_P2_X: ""

  L1_T_1: ""
  L1_T_2: ""
  L1_T_B: ""
  L1_T_C: ""
  L1_T_M: ""
  T_M: ""

  L1_C_1: ""
  L1_C_2: ""
  L1_C_B: ""
  L1_C_C: ""
  L1_C_M: ""
  L2_P2_C: ""
