---
# Restoration Druid

# - [1, "C_Spell.PickupSpell(774)"]  # Rejuvenation
# - [2, "C_Spell.PickupSpell(8936)"]  # Regrowth

# - [5, "C_Spell.PickupSpell(48438)"]  # Wild Growth
# - [6, "C_Spell.PickupSpell(102401)"]  # Wild Charge

# - [13, "PickupMacro(120 + 12)"]  # Rejuvenation
# - [14, "PickupMacro(120 + 16)"]  # Regrowth

# - [17, "PickupMacro(120 + 13)"]  # Wild Growth
# - [18, "PickupMacro(120 + 8)"]  # Wild Charge [help]

# - [3, "C_Spell.PickupSpell(88423)"]  # Remove Corruption
# - [4, "C_Spell.PickupSpell(102351)"]  # Cenarion Ward
# - [7, "C_Spell.PickupSpell(33763)"]  # Lifebloom
# - [8, "C_Spell.PickupSpell(102693)"]  # Grove Guardians
# - [9, "C_Spell.PickupSpell(145205)"]  # Efflorescence
# - [10, "C_Spell.PickupSpell(18562)"]  # Swiftmend
# - [11, "C_Spell.PickupSpell(203651)"]  # Overgrowth
# - [12, "C_Spell.PickupSpell(102342)"]  # Ironbark

# - [15, "PickupMacro(120 + 10)"]  # Remove Corruption
# - [16, "PickupMacro(120 + 17)"]  # Cenarion Ward
# - [19, "PickupMacro(120 + 9)"]  # Lifebloom
# - [20, "PickupMacro(120 + 19)"]  # Grove Guardians
# - [21, "PickupMacro(120 + 21)"]  # Efflorescence
# - [22, "PickupMacro(120 + 14)"]  # Swiftmend
# - [23, "PickupMacro(120 + 15)"]  # Overgrowth
# - [24, "PickupMacro(120 + 18)"]  # Ironbark

# - [25, "C_Spell.PickupSpell(33891)"]  # incarn tree
# - [26, "C_Spell.PickupSpell(740)"]
# - [49, "C_Spell.PickupSpell(33786)"]
# - [50, "C_Spell.PickupSpell(339)"]

# - [55, "C_Spell.PickupSpell(197626)"]

# - [57, "C_Spell.PickupSpell(8921)"]
# - [58, "C_Spell.PickupSpell(108238)"]
# - [59, "C_Spell.PickupSpell(106898)"]
# - [60, "C_Spell.PickupSpell(22812)"]
# - [61, "C_Spell.PickupSpell(5176)"]  # wrath

# - [63, "C_Spell.PickupSpell(197628)"]
# - [64, "C_Spell.PickupSpell(319454)"]
# - [65, "C_Spell.PickupSpell(1850)"]
# - [66, "C_Spell.PickupSpell(20484)"]
# - [67, "C_Spell.PickupSpell(132469)"]  # typhoon

# Nature's Swiftness
# - [56, "C_Spell.PickupSpell(132158)"]

# Ursol's Vortex
# - [62, "C_Spell.PickupSpell(102793)"]
# - [68, "PickupMacro(120 + 20)"]

# Forms
# - [44, "PickupMacro(120 + 6)"]
# - [38, "PickupMacro(120 + 5)"]
# - [32, "PickupMacro(120 + 2)"]
# - [31, "PickupMacro(120 + 4)"]
# - [37, "PickupMacro(120 + 3)"]

# - [41, "C_Spell.PickupSpell(212040)"]
# - [46, "PickupMacro(120 + 11)"]

# Bear Form
# - [97, "C_Spell.PickupSpell(33917)"]
# - [98, "C_Spell.PickupSpell(8936)"]
# - [99, "C_Spell.PickupSpell(192081)"]
# - [100, "C_Spell.PickupSpell(213764)"]
# - [102, "C_Spell.PickupSpell(102401)"]
# - [103, "C_Spell.PickupSpell(22842)"]
# - [104, "C_Spell.PickupSpell(102693)"]
# - [105, "C_Spell.PickupSpell(6795)"]

# Cat Form
# - [73, "C_Spell.PickupSpell(5221)"]
# - [74, "C_Spell.PickupSpell(8936)"]
# - [75, "C_Spell.PickupSpell(22570)"]
# - [76, "C_Spell.PickupSpell(213764)"]
# - [78, "C_Spell.PickupSpell(102401)"]
# - [79, "C_Spell.PickupSpell(1822)"]
# - [80, "C_Spell.PickupSpell(102693)"]
# - [81, "C_Spell.PickupSpell(1079)"]
# - [82, "C_Spell.PickupSpell(22568)"]
array:
  # PADRSHOULDER column
  - [67, C_Spell.PickupSpell("Typhoon")]
  - [61, C_Spell.PickupSpell("Wrath")]

  - [7, PickupMacro(120 + 13)]
  - [19, C_Spell.PickupSpell(33763)]  # bar 2, "Lifebloom" doesn't work
  - [103, C_Spell.PickupSpell("Swipe")]  # bear
  - [79, C_Spell.PickupSpell("Swipe")]  # cat

  - [1, PickupMacro(120 + 24)]
  - [13, C_Spell.PickupSpell("Rejuvenation")]  # bar 2
  - [97, C_Spell.PickupSpell("Mangle")]  # bear
  - [73, C_Spell.PickupSpell("Rake")]  # cat

  - [55, C_Spell.PickupSpell("Starsurge")]
  - [25, 'C_Spell.PickupSpell("Incarnation: Tree of Life")']

  # PADRTRIGGER column
  - [68, PickupMacro(120 + 21)]  # self ursol's
  - [62, C_Spell.PickupSpell("Ursol's Vortex")]

  - [8, PickupMacro(120 + 20)]
  - [20, C_Spell.PickupSpell("Grove Guardians")]  # bar 2
  - [104, PickupMacro(120 + 20)]  # bear
  - [80, PickupMacro(120 + 20)]  # cat

  - [2, PickupMacro(120 + 17)]
  - [14, C_Spell.PickupSpell("Regrowth")]  # bar 2
  - [98, PickupMacro(120 + 17)]  # bear
  - [74, PickupMacro(120 + 17)]  # cat

  - [56, C_Spell.PickupSpell("Nature's Swiftness")]
  - [26, C_Spell.PickupSpell("Tranquility")]

  # PAD3 column
  - [69, C_Spell.PickupSpell("Frenzied Regeneration")]
  - [63, C_Spell.PickupSpell("Starfire")]

  - [9, PickupMacro(120 + 22)]
  - [21, C_Spell.PickupSpell("Efflorescence")]  # bar 2
  - [105, C_Spell.PickupSpell("Growl")]  # bear
  - [81, C_Spell.PickupSpell("Rip")]  # cat

  - [3, PickupMacro(120 + 12)]
  - [15, C_Spell.PickupSpell("Nature's Cure")]  # bar 2
  - [99, C_Spell.PickupSpell("Frenzied Regeneration")]  # bear
  - [75, C_Spell.PickupSpell("Maim")]  # cat

  - [57, C_Spell.PickupSpell("Moonfire")]
  # - [51, ""]
  # - [27, ""]

  # PAD1 column
  # - [70, ""]
  - [64, ""]

  - [10, PickupMacro(120 + 15)]
  - [22, C_Spell.PickupSpell("Swiftmend")]  # bar 2
  - [106, PickupMacro(120 + 15)]  # bear
  - [82, C_Spell.PickupSpell("Ferocious Bite")]  # cat

  - [4, PickupMacro(120 + 18)]
  - [16, C_Spell.PickupSpell("Cenarion Ward")]  # bar 2
  - [100, C_Spell.PickupSpell("Ironfur")]  # bear
  - [76, C_Spell.PickupSpell("Shred")]  # cat

  - [58, ""]
  # - [52, ""]
  # - [28, ""]

  # PAD4 column
  # - [71, ""]

  - [11, PickupMacro(120 + 16)]
  - [23, C_Spell.PickupSpell("Overgrowth")]  # bar 2
  - [107, PickupMacro(120 + 16)]  # bear
  - [83, PickupMacro(120 + 16)]  # cat

  - [5, PickupMacro(120 + 14)]
  - [17, C_Spell.PickupSpell("Wild Growth")]  # bar 2
  - [101, PickupMacro(120 + 14)]  # bear
  - [77, PickupMacro(120 + 14)]  # cat

  - [59, ""]
  # - [53, ""]
  # - [29, ""]

  # PAD2 column
  # - [72, ""]
  - [66, C_Spell.PickupSpell("Rebirth")]

  - [12, PickupMacro(120 + 19)]
  - [24, C_Spell.PickupSpell("Ironbark")]  # bar 2
  - [108, PickupMacro(120 + 19)]  # bear
  - [84, PickupMacro(120 + 19)]  # cat

  # - [54, ""]
  - [30, C_Spell.PickupSpell("Revitalize")]

  # d-pad (up)
  - [47, C_Spell.PickupSpell("Revive")]
