---
# Restoration Druid
array:
  # PADRSHOULDER column
  - [67, C_Spell.PickupSpell("Typhoon")]
  - [61, C_Spell.PickupSpell("Wrath")]

  - [7, PickupMacro(120 + 19)]
  - [19, C_Spell.PickupSpell(33763)]  # bar 2, "Lifebloom" doesn't work
  - [103, C_Spell.PickupSpell("Swipe")]  # bear
  - [79, C_Spell.PickupSpell("Rake")]  # cat

  - [1, PickupMacro(120 + 25)]
  - [13, C_Spell.PickupSpell("Rejuvenation")]  # bar 2
  - [97, C_Spell.PickupSpell("Mangle")]  # bear
  - [73, C_Spell.PickupSpell("Shred")]  # cat

  - [55, C_Spell.PickupSpell("Mighty Bash")]  # Starsurge
  - [25, PickupMacro(120 + 11)]  # tree/convoke

  # PADRTRIGGER column
  - [68, PickupMacro(120 + 21)]  # self ursol's
  - [62, PickupMacro(120 + 10)]  # mass root / ursol's

  - [8, PickupMacro(120 + 20)]  # self nourish / guardians
  - [20, PickupMacro(120 + 9)]  # bar 2, nourish / guardians
  - [104, PickupMacro(120 + 20)]  # bear
  - [80, PickupMacro(120 + 20)]  # cat

  - [2, PickupMacro(120 + 17)]
  - [14, C_Spell.PickupSpell("Regrowth")]  # bar 2
  - [98, PickupMacro(120 + 17)]  # bear
  - [74, PickupMacro(120 + 17)]  # cat

  - [56, C_Spell.PickupSpell("Nature's Swiftness")]
  - [26, C_Spell.PickupSpell("Tranquility")]

  # PAD3 column
  - [69, C_Spell.PickupSpell("Frenzied Regeneration")]
  - [63, C_Spell.PickupSpell("Invigorate")]  # Starfire

  - [9, PickupMacro(120 + 22)]
  - [21, C_Spell.PickupSpell("Efflorescence")]  # bar 2
  - [105, C_Spell.PickupSpell("Growl")]  # bear
  - [81, C_Spell.PickupSpell("Rip")]  # cat

  - [3, PickupMacro(120 + 27)]
  - [15, C_Spell.PickupSpell("Nature's Cure")]  # bar 2
  - [99, C_Spell.PickupSpell("Frenzied Regeneration")]  # bear
  - [75, C_Spell.PickupSpell("Maim")]  # cat

  - [57, C_Spell.PickupSpell("Moonfire")]
  # - [51, ""]
  - [27, PickupMacro(120 + 24)]  # self innervate

  # PAD1 column
  # - [70, ""]
  - [64, ""]

  - [10, PickupMacro(120 + 28)]
  - [22, C_Spell.PickupSpell("Swiftmend")]  # bar 2
  - [106, PickupMacro(120 + 28)]  # bear
  - [82, C_Spell.PickupSpell("Ferocious Bite")]  # cat

  - [4, PickupMacro(120 + 18)]
  - [16, C_Spell.PickupSpell("Cenarion Ward")]  # bar 2
  - [100, PickupMacro(120 + 18)]  # bear, Ironfur
  - [76, C_Spell.PickupSpell("Swipe")]  # cat

  - [58, ""]
  # - [52, ""]
  # - [28, ""]

  # PAD4 column
  # - [71, ""]

  - [11, PickupMacro(120 + 16)]
  - [23, C_Spell.PickupSpell("Overgrowth")]  # bar 2
  - [107, PickupMacro(120 + 16)]  # bear
  - [83, PickupMacro(120 + 16)]  # cat

  - [5, PickupMacro(120 + 14)]
  - [17, C_Spell.PickupSpell("Wild Growth")]  # bar 2
  - [101, PickupMacro(120 + 14)]  # bear
  - [77, PickupMacro(120 + 14)]  # cat

  - [59, ""]
  # - [53, ""]
  # - [29, ""]

  # PAD2 column
  # - [72, ""]
  - [66, C_Spell.PickupSpell("Rebirth")]

  - [12, PickupMacro(120 + 26)]
  - [24, C_Spell.PickupSpell("Ironbark")]  # bar 2
  - [108, PickupMacro(120 + 26)]  # bear
  - [84, PickupMacro(120 + 26)]  # cat

  # - [54, ""]
  - [30, C_Spell.PickupSpell("Revitalize")]

  # d-pad (up)
  - [47, C_Spell.PickupSpell("Revive")]
