---
# Devastation Evoker
by_key:
  L2_R2: m slf

  L2_R1: s 357208  # Fire Breath

  L1_R1_1: s "Living Flame"
  L1_R1_2: m flf

  R1_1: s "Azure Strike"
  R1_2: s "Azure Strike"

  P2_R1: s "Shattering Star"
  L1_P2_R1: s "Dragonrage"

  L2_P2_R2: s 357210  # Deep Breath

  L1_R2_1: s "Pyre"
  L1_R2_2: s "Pyre"

  R2_1: s "Disintegrate"
  R2_2: s "Disintegrate"

  P2_R2: s 359073  # Eternity Surge

  L2_S: s "Unravel"

  L1_S_1: m seb
  L1_S_2: s "Emerald Blossom"

  S_1: m sx
  S_2: s "Expunge"

  X_1: m sve
  X_2: s "Verdant Embrace"

  P2_T: s "Firestorm"
