---
# Preservation Evoker
by_key:
  L2_L1_R1: m dfs
  L2_R1: s "Fire Breath"

  L1_R1_1: m sve
  L1_R1_2: s "Verdant Embrace"

  R1_1: m slf
  R1_2: m flf

  P2_R1: m elf  # living flame harm

  L2_R2: s "Dream Breath"

  L1_R2_1: m sr
  L1_R2_2: s "Reversion"

  R2_1: m se
  R2_2: s "Echo"

  P2_R2: s "Azure Strike"

  L1_S_1: m seb
  L1_S_2: s "Emerald Blossom"

  L2_S: s "Rewind"
  S_1: m sn
  S_2: s "Naturalize"
  P2_S: s "Disintegrate"

  # L2_X: s "Temporal Anomaly"
  X_1: m std
  X_2: s "Time Dilation"

  P2_T: s "Temporal Anomaly"

  L1_C_1: s "Emerald Communion"
  L1_C_2: s "Emerald Communion"
  C_1: s "Dream Projection"
  C_2: s "Dream Projection"

  L1_P2_C: s "Mass Return"
