---
# Preservation Evoker
by_key:
  L2_R1: s "Fire Breath"

  L1_R1_1: m sve
  L1_R1_2: s "Verdant Embrace"

  R1_1: m slf
  R1_2: m flf

  P2_R1: s "Disintegrate"
  L1_P2_R1: s "Stasis"

  L2_R2: s "Dream Breath"

  L1_R2_1: m sr
  L1_R2_2: s "Reversion"

  R2_1: m se
  R2_2: s "Echo"

  P2_R2: s "Azure Strike"

  L1_S_1: m seb
  L1_S_2: s "Emerald Blossom"

  L2_S: m elf  # living flame harm

  S_1: m sn
  S_2: s "Naturalize"

  L2_X: s "Rewind"

  X_1: m ssb
  X_2: s "Spiritbloom"

  L2_T: s "Emerald Communion"

  P2_T: s "Dream Projection"

  L2_C: s "Dream Flight"

  L1_C_1: m std
  L1_C_2: s "Time Dilation"

  L1_P2_C: s "Mass Return"

  P2_P3: s "Temporal Anomaly"
