---
by_key:
  L1_R1_1: s "Soul Immolation"
  L1_R1_2: s "Soul Immolation"
  L2_R1: s "Void Ray"
  R1_1: s "Reap"
  R1_2: s "Reap"

  L2_R2: s "Shift"
  L1_R2_1: s "Voidblade"
  L1_R2_2: s "Voidblade"
  R2_1: s "Consume"
  R2_2: s "Consume"
  L2_P2_R2: s "Void Nova"

  S_1: s "Void Metamorphosis"
  S_2: s "Void Metamorphosis"
