---
# Marksmanship Hunter
by_key:
  L1_P2_R1: s "Trueshot"
  L1_R1_1: s "Arcane Shot"
  L1_R1_2: s "Arcane Shot"
  R1_1: s "Rapid Fire"
  R1_2: s "Rapid Fire"
  P2_R1: m ks

  R2_1: s "Aimed Shot"
  R2_2: s "Aimed Shot"

  L2_R2: s "Multi-Shot"
  L1_P2_R2: s "Steady Shot"

  S_1: m sv
  S_2: s "Volley"
  L2_P2_S: s "Harrier's Cry"

  L1_P2_T: s "Eagle Eye"
