---
# Holy Priest
by_key:
  L2_L1_R1: s "Divine Ascension"
  L1_R1_1: m spom
  L1_R1_2: s "Prayer of Mending"
  R1_1: m sr
  R1_2: s "Renew"
  L1_P2_R1: s 428924  # "Premonition of Insight"

  L1_R2_1: m shwy
  L1_R2_2: 's "Holy Word: Sanctify"'
  L2_R2: 's "Holy Word: Chastise"'
  R2_1: m sfh
  R2_2: s "Flash Heal"
  L1_P2_R2: s "Divine Word"

  L2_S: s "Divine Hymn"
  S_1: m sp
  S_2: s "Purify"
  P2_S: s "Holy Fire"
  L1_P2_S: s "Smite"

  L2_L1_X: s "Symbol of Hope"

  L2_L1_T: s "Lightwell"
  L2_T: s 215769  # "Spirit of Redemption"
  L1_T_1: m sgs
  L1_T_2: s "Guardian Spirit"
  T_1: m shws
  T_2: 's "Holy Word: Serenity"'
  P2_T: s "Apotheosis"
  L2_P2_T: s "Holy Ward"

  L2_L1_C: s "Greater Heal"
  L2_C: m spoh
  C_1: m sh
  C_2: s "Heal"
  P2_C: s "Prayer of Healing"
  L2_P2_C: m sroh
  L1_P2_C: s "Ray of Hope"
