---
# Subtlety Rogue
by_key:
  L2_R1: m ess

  L1_R1_1: s "Symbols of Death"
  L1_R1_2: s "Symbols of Death"
  L1_R1_C: s "Symbols of Death"

  R1_1: s "Backstab"
  R1_2: s "Backstab"
  R1_C: s "Shadowstrike"

  L1_R2_1: s "Rupture"
  L1_R2_2: s "Rupture"
  L1_R2_C: s "Rupture"

  R2_1: s "Eviscerate"
  R2_2: s "Eviscerate"
  R2_C: s "Eviscerate"

  L2_L1_S: s "Shuriken Tornado"

  L2_S: s "Shadow Blades"

  L1_S_1: s "Black Powder"
  L1_S_2: s "Black Powder"
  L1_S_C: s "Black Powder"

  S_1: s "Shuriken Storm"
  S_2: s "Shuriken Storm"
  S_C: s "Shuriken Storm"

  P2_S: s "Goremaw's Bite"

  L2_P2_S: s "Flagellation"

  L2_L1_P1: s "Shuriken Toss"

  L2_R2: m fss

  L2_P2_T: s "Ambush"

  L1_C_1: s "Secret Technique"
  L1_C_2: s "Secret Technique"
  L1_C_C: s "Secret Technique"

  P2_C: s "Shadow Dance"
