---
# Elemental Shaman
array:
  # PADRSHOULDER column
  # - [67, ""]
  - [61, C_Spell.PickupSpell("Primordial Wave")]

  - [7, C_Spell.PickupSpell("Earth Shock")]
  - [19, C_Spell.PickupSpell("Earth Shock")]  # bar 2

  - [1, C_Spell.PickupSpell("Flame Shock")]
  - [13, C_Spell.PickupSpell("Flame Shock")]  # bar 2

  - [55, C_Spell.PickupSpell("Lightning Bolt")]
  # - [49, ""]
  - [25, C_Spell.PickupSpell("Healing Stream Totem")]

  # PADRTRIGGER column
  # - [68, ""]
  - [62, C_Spell.PickupSpell("Frost Shock")]

  - [8, PickupMacro(120 + 19)]
  - [20, C_Spell.PickupSpell("Earthquake")]  # bar 2

  - [2, C_Spell.PickupSpell("Lava Burst")]
  - [14, C_Spell.PickupSpell("Lava Burst")]  # bar 2

  - [56, C_Spell.PickupSpell("Nature's Swiftness")]
  # - [50, ""]
  # - [26, ""]

  # PAD3 column
  - [69, C_Spell.PickupSpell("Fire Elemental")]
  - [63, C_Spell.PickupSpell("Chain Lightning")]

  - [9, C_Spell.PickupSpell("Stormkeeper")]
  - [21, C_Spell.PickupSpell("Stormkeeper")]  # bar 2

  - [3, PickupMacro(120 + 21)]
  - [15, C_Spell.PickupSpell("Liquid Magma Totem")]  # bar 2

  - [57, C_Spell.PickupSpell("Ascendance")]
  # - [51, ""]
  # - [27, ""]

  # PAD1 column
  # - [70, ""]
  # - [64, ""]

  - [10, PickupMacro(120 + 10)]
  - [22, C_Spell.PickupSpell("Thunderstorm")]  # bar 2

  - [4, PickupMacro(120 + 9)]
  - [16, C_Spell.PickupSpell("Earth Shield")]  # bar 2

  # - [58, ""]
  # - [52, ""]
  # - [28, ""]

  # PAD4 column
  # - [71, ""]
  # - [65, ""]

  - [11, C_Spell.PickupSpell("Earth Elemental")]
  - [23, C_Spell.PickupSpell("Earth Elemental")]  # bar 2

  - [5, PickupMacro(120 + 5)]
  - [17, C_Spell.PickupSpell("Healing Surge")]  # bar 2

  # - [59, ""]
  # - [53, ""]
  # - [29, ""]

  # PAD2 column
  # - [72, ""]
  # - [66, ""]

  - [12, PickupMacro(120 + 18)]
  - [24, C_Spell.PickupSpell("Earthgrab Totem")]  # bar 2

  - [6, PickupMacro(120 + 13)]
  - [18, C_Spell.PickupSpell("Totemic Projection")]  # bar 2

  - [60, C_Spell.PickupSpell("Tremor Totem")]
  - [54, C_Spell.PickupSpell("Lightning Shield")]
  - [30, C_Spell.PickupSpell("Flametongue Weapon")]

  # paddles (left)
  - [43, ""]
  - [37, ""]
  - [31, ""]
  # paddles (right)
  - [44, C_Spell.PickupSpell("Spiritwalker's Grace")]
  - [38, C_Spell.PickupSpell("Gust of Wind")]
  # - [32, ""]

  # d-pad (left)
  # - [45, ""]
  # - [39, ""]
  # - [33, ""]
  # d-pad (down)
  # - [46, ""]
  # - [40, ""]
  # - [34, ""]
  # d-pad (up)
  - [47, C_Spell.PickupSpell("Ancestral Spirit")]
  # - [41, ""]
  # - [35, ""]
  # d-pad (right)
  # - [48, ""]
  # - [42, ""]
  # - [36, ""]
