---
# Restoration Shaman
by_key:
  L1_R1_1: m sul
  L1_R1_2: s "Unleash Life"
  R1_1: m sr
  R1_2: s "Riptide"
  P2_R1: s "Flame Shock"
  L1_P2_R1: s "Lightning Bolt"

  L2_R2: s "Lava Burst"
  L1_R2_1: m shw
  L1_R2_2: s "Healing Wave"
  R2_1: m shs
  R2_2: s "Healing Surge"

  L2_S: m ahtt
  S_1: m sps
  S_2: s "Purify Spirit"
  L2_P2_S: s "Heroism"  # could do this with a macro
  # L1_P2_S: s "Chain Lightning"

  # L1_X_1: m sewt
  # L1_X_2: s "Earthen Wall Totem"

  L1_T_1: m sslt
  L1_T_2: s "Spirit Link Totem"
  T_1: m sch
  T_2: s "Chain Heal"

  C_1: m shr
  C_2: s "Healing Rain"
  L2_P2_C: s "Water Shield"

  L1_P2_T: s "Earthliving Weapon"
