---
# Affliction Warlock
# set these with felhunter out
by_key:
  L1_R1_1: s "Unstable Affliction"
  L1_R1_2: s "Unstable Affliction"
  R1_1: s "Corruption"
  R1_2: s "Corruption"
  P2_R1: s "Shadow Bolt"

  L1_R2_1: s "Haunt"
  L1_R2_2: s "Haunt"

  R2_1: m ar
  R2_2: m ar

  # L2_L1_S: s "Oblivion"

  L2_S: s "Summon Darkglare"

  # S_1: s "Agony"
  # S_2: s "Agony"

  P2_S: s "Dark Harvest"

  P2_X: s "Soul Swap"

  # L2_L1_T: s "Soul Swap"

  # L1_T_1: s "Phantom Singularity"
  # L1_T_2: s "Phantom Singularity"

  C_1: s "Seed of Corruption"
  C_2: s "Seed of Corruption"

  L2_P3: s "Grimoire of Sacrifice"
