---
# Destruction Warlock
# set these with felhunter out
by_key:
  L1_R1_1: m cfr
  L1_R1_2: m cfr

  R1_1: s "Immolate"
  R1_2: s "Immolate"

  P2_R1: m inc  # Incinerate (can't pick up for some reason)

  L1_R2_1: m srof
  L1_R2_2: s "Rain of Fire"

  R2_1: s "Chaos Bolt"
  R2_2: s "Chaos Bolt"

  L2_S: s "Shadowburn"

  P2_S: s "Havoc"

  L2_X: s "Channel Demonfire"
  P2_X: s "Soul Fire"

  L1_C_1: m ssi
  L1_C_2: s "Summon Infernal"

  C_1: m sca
  C_2: s "Cataclysm"

  L2_P3: s "Grimoire of Sacrifice"
