---
# Windwalker Monk
array:
  # PADRSHOULDER column
  # - [67, ""]
  - [61, C_Spell.PickupSpell("Whirling Dragon Punch")]

  - [7, C_Spell.PickupSpell("Fists of Fury")]
  - [19, C_Spell.PickupSpell("Fists of Fury")]  # bar 2

  - [1, C_Spell.PickupSpell("Tiger Palm")]
  - [13, C_Spell.PickupSpell("Tiger Palm")]  # bar 2

  - [55, C_Spell.PickupSpell("Flying Serpent Kick")]
  # - [49, ""]
  - [25, 'C_Spell.PickupSpell("Storm, Earth, and Fire")']

  # PADRTRIGGER column
  - [68, C_Spell.PickupSpell("Clash")]
  - [62, C_Spell.PickupSpell("Strike of the Windlord")]

  - [8, C_Spell.PickupSpell("Blackout Kick")]
  - [20, C_Spell.PickupSpell("Blackout Kick")]  # bar 2

  - [2, C_Spell.PickupSpell("Rising Sun Kick")]
  - [14, C_Spell.PickupSpell("Rising Sun Kick")]  # bar 2

  # - [56, ""]
  # - [50, ""]
  # - [26, ""]

  # PAD3 column
  # - [69, ""]
  - [63, 'C_Spell.PickupSpell("Invoke Xuen, the White Tiger")']

  - [9, PickupMacro(120 + 5)]
  - [21, C_Spell.PickupSpell("Detox")]  # bar 2

  - [3, PickupMacro(120 + 6)]
  - [15, C_Spell.PickupSpell("Vivify")]  # bar 2

  - [57, ""]
  # - [51, ""]
  # - [27, ""]

  # PAD1 column
  # - [70, ""]
  # - [64, ""]

  # - [10, ""]
  # - [22, ""]  # bar 2

  # - [4, ""]
  # - [16, ""]  # bar 2

  # - [58, ""]
  # - [52, ""]
  # - [28, ""]

  # PAD4 column
  # - [71, ""]
  # - [65, ""]

  # - [11, ""]
  # - [23, ""]  # bar 2

  # - [5, ""]
  # - [17, ""]  # bar 2

  - [59, ""]
  # - [53, ""]
  # - [29, ""]

  # PAD2 column
  # - [72, ""]
  - [66, ""]

  - [12, C_Spell.PickupSpell("Touch of Karma")]
  - [24, C_Spell.PickupSpell("Touch of Karma")]  # bar 2

  # - [6, ""]
  # - [18, ""]  # bar 2

  - [60, ""]
  # - [54, ""]
  # - [30, ""]

  # paddles (left)
  - [43, ""]
  - [37, ""]
  - [31, ""]
  # paddles (right)
  - [44, ""]
  # - [38, ""]
  - [32, C_Spell.PickupSpell("Roll")]

  # d-pad (left)
  # - [45, ""]
  # - [39, ""]
  # - [33, ""]
  # d-pad (down)
  - [46, ""]
  # - [40, ""]
  # - [34, ""]
  # d-pad (up)
  # - [47, ""]
  # - [41, ""]
  # - [35, ""]
  # d-pad (right)
  # - [48, ""]
  # - [42, ""]
  # - [36, ""]
