---
# Mistweaver Monk
array:
  # PADRSHOULDER column
  # - [67, ""]
  - [61, C_Spell.PickupSpell("Blackout Kick")]

  - [7, PickupMacro(120 + 6)]
  - [19, C_Spell.PickupSpell("Vivify")]  # bar 2

  - [1, PickupMacro(120 + 13)]
  - [13, C_Spell.PickupSpell("Soothing Mist")]  # bar 2

  - [55, C_Spell.PickupSpell("Thunder Focus Tea")]
  # - [49, ""]
  - [25, 'C_Spell.PickupSpell("Invoke Chi-Ji, the Red Crane")']

  # PADRTRIGGER column
  - [68, C_Spell.PickupSpell("Restoral")]
  - [62, C_Spell.PickupSpell("Rising Sun Kick")]

  - [8, PickupMacro(120 + 8)]
  - [20, C_Spell.PickupSpell("Enveloping Mist")]  # bar 2

  - [2, PickupMacro(120 + 9)]
  - [14, C_Spell.PickupSpell("Renewing Mist")]  # bar 2

  # - [56, ""]
  # - [50, ""]
  # - [26, ""]

  # PAD3 column
  # - [69, ""]
  - [63, C_Spell.PickupSpell("Tiger Palm")]

  - [9, PickupMacro(120 + 14)]
  - [21, C_Spell.PickupSpell("Summon Jade Serpent Statue")]

  - [3, PickupMacro(120 + 5)]
  - [15, C_Spell.PickupSpell("Detox")]  # bar 2

  - [57, C_Spell.PickupSpell("Mana Tea")]
  # - [51, ""]
  # - [27, ""]

  # PAD1 column
  # - [70, ""]
  # - [64, ""]

  # - [10, ""]
  # - [22, ""]  # bar 2

  # - [4, ""]
  # - [16, ""]  # bar 2

  # - [58, ""]
  # - [52, ""]
  # - [28, ""]

  # PAD4 column
  # - [71, ""]
  # - [65, ""]

  # - [11, ""]
  # - [23, ""]  # bar 2

  - [5, PickupMacro(120 + 12)]
  - [17, PickupMacro(120 + 4)]  # bar 2, Zen Spheres help

  # - [59, ""]
  # - [53, ""]
  # - [29, ""]

  # PAD2 column
  # - [72, ""]
  - [66, PickupMacro(120 + 3)]  # Zen Spheres harm

  - [12, PickupMacro(120 + 11)]
  - [24, C_Spell.PickupSpell("Life Cocoon")]  # bar 2

  - [6, ""]
  - [18, ""]  # bar 2

  - [60, ""]
  # - [54, ""]
  - [30, ""]

  # paddles (left)
  - [43, ""]
  - [37, ""]
  - [31, ""]
  # paddles (right)
  - [44, ""]
  # - [38, ""]
  - [32, C_Spell.PickupSpell("Chi Torpedo")]

  # d-pad (left)
  # - [45, ""]
  # - [39, ""]
  # - [33, ""]
  # d-pad (down)
  - [46, C_Spell.PickupSpell("Reawaken")]
  # - [40, ""]
  # - [34, ""]
  # d-pad (up)
  # - [47, ""]
  # - [41, ""]
  # - [35, ""]
  # d-pad (right)
  # - [48, ""]
  # - [42, ""]
  # - [36, ""]
