---
# Holy Paladin
array:
  # PADRSHOULDER column
  - [67, C_Spell.PickupSpell("Rebuke")]
  - [61, C_Spell.PickupSpell("Judgment")]

  - [7, PickupMacro(120 + 6)]
  - [19, C_Spell.PickupSpell("Flash of Light")]  # bar 2

  - [1, PickupMacro(120 + 5)]  # holy shock
  - [13, C_Spell.PickupSpell("Holy Shock")]  # bar 2

  - [55, C_Spell.PickupSpell("Crusader Strike")]
  - [49, C_Spell.PickupSpell("Blinding Light")]
  - [25, C_Spell.PickupSpell("Divine Toll")]

  # PADRTRIGGER column
  - [68, C_Spell.PickupSpell("Shield of the Righteous")]
  - [62, C_Spell.PickupSpell("Light of Dawn")]

  - [8, PickupMacro(120 + 7)]
  - [20, C_Spell.PickupSpell("Holy Light")]  # bar 2

  - [2, PickupMacro(120 + 11)]
  - [14, C_Spell.PickupSpell("Word of Glory")]  # bar 2

  - [56, C_Spell.PickupSpell("Hammer of Justice")]
  - [50, C_Spell.PickupSpell("Blessing of Sacrifice")]
  - [26, C_Spell.PickupSpell("Avenging Wrath")]

  # PAD3 column
  # - [69, ""]
  - [63, C_Spell.PickupSpell("Beacon of Faith")]

  - [9, PickupMacro(120 + 8)]
  - [21, C_Spell.PickupSpell("Beacon of Light")]  # bar 2

  - [3, PickupMacro(120 + 9)]
  - [15, C_Spell.PickupSpell("Cleanse")]  # bar 2

  - [57, C_Spell.PickupSpell("Aura Mastery")]
  # - [51, ""]
  # - [27, ""]

  # PAD1 column
  # - [70, ""]
  - [64, C_Spell.PickupSpell("Divine Shield")]

  - [10, PickupMacro(120 + 12)]
  - [22, C_Spell.PickupSpell(633)]  # bar 2, "Lay on Hands"

  - [4, PickupMacro(120 + 10)]
  - [16, C_Spell.PickupSpell("Barrier of Faith")]  # bar 2

  - [58, C_Spell.PickupSpell("Consecration")]
  # - [52, ""]
  - [28, C_Spell.PickupSpell("Hand of Reckoning")]

  # PAD4 column
  # - [71, ""]
  # - [65, ""]

  - [11, PickupMacro(120 + 13)]
  - [23, C_Spell.PickupSpell("Blessing of Protection")]  # bar 2

  - [5, PickupMacro(120 + 17)]
  - [17, C_Spell.PickupSpell("Holy Bulwark")]  # bar 2

  # - [59, ""]
  # - [53, ""]
  # - [29, ""]

  # PAD2 column
  # - [72, ""]
  - [66, C_Spell.PickupSpell("Intercession")]

  - [12, PickupMacro(120 + 15)]
  - [24, C_Spell.PickupSpell("Blessing of Summer")]  # bar 2

  - [6, PickupMacro(120 + 14)]
  - [18, C_Spell.PickupSpell("Blessing of Freedom")]  # bar 2

  - [60, C_Spell.PickupSpell("Divine Protection")]
  # - [54, ""]
  - [30, C_Spell.PickupSpell("Absolution")]

  # paddles (left)
  # - [43, ""]
  # - [37, ""]
  # - [31, ""]
  # paddles (right)
  - [44, PickupMacro(120 + 4)]  # holy shock help
  - [38, PickupMacro(120 + 3)]  # holy shock harm
  # - [32, ""]

  # d-pad (left)
  # - [45, ""]
  # - [39, ""]
  # - [33, ""]
  # d-pad (down)
  - [46, C_Spell.PickupSpell("Rite of Sanctification")]
  # - [40, ""]
  # - [34, ""]
  # d-pad (up)
  # - [47, ""]
  # - [41, ""]
  # - [35, ""]
  # d-pad (right)
  # - [48, ""]
  # - [42, ""]
  # - [36, ""]
