---
# Retribution Paladin
by_key:
  L2_R1: s 24275

  L1_R1_1: s 20271
  L1_R1_2: s 20271

  R1_1: s 184575
  R1_2: s 184575

  P2_R1: s 255937

  L2_L1_R2: m sfr  # self final reckoning
  L2_R2: s 343721

  L1_R2_1: s 53385
  L1_R2_2: s 53385

  R2_1: s 383328
  R2_2: s 383328

  L1_P2_R2: s "Divine Hammer"

  L2_S: s 184662

  S_1: m swog  # word of glory
  S_2: s 85673

  X_1: m sfol  # flash of light
  X_2: s 19750

  T_1: m sbos  # self sanc
  T_2: s "Blessing of Sanctuary"

  L1_C_1: m sct
  L1_C_2: s "Cleanse Toxins"
