---
by_key:
  L2_L1_R1: ""
  L2_R1: ""
  L1_R1_1: ""
  L1_R1_2: ""
  # druid forms
  # L1_R1_B: ""
  # L1_R1_C: ""
  # L1_R1_M: ""
  R1_1: ""
  R1_2: ""
  # druid forms
  # R1_B: ""
  # R1_C: ""
  # R1_M: ""
  P2_R1: ""
  L2_P2_R1: ""
  L1_P2_R1: ""

  L2_L1_R2: ""
  L2_R2: ""
  L1_R2_1: ""
  L1_R2_2: ""
  # druid forms
  # L1_R2_B: ""
  # L1_R2_C: ""
  # L1_R2_M: ""
  R2_1: ""
  R2_2: ""
  # druid forms
  # R2_B: ""
  # R2_C: ""
  # R2_M: ""
  P2_R2: ""
  L2_P2_R2: ""
  L1_P2_R2: ""

  L2_L1_S: ""
  L2_S: ""
  L1_S_1: ""
  L1_S_2: ""
  # druid forms
  # L1_S_B: ""
  # L1_S_C: ""
  # L1_S_M: ""
  S_1: ""
  S_2: ""
  # druid forms
  # S_B: ""
  # S_C: ""
  # S_M: ""
  P2_S: ""
  L2_P2_S: ""
  L1_P2_S: ""

  L2_L1_X: ""
  L2_X: ""
  L1_X_1: ""
  L1_X_2: ""
  # druid forms
  # L1_X_B: ""
  # L1_X_C: ""
  # L1_X_M: ""
  X_1: ""
  X_2: ""
  # druid forms
  # X_B: ""
  # X_C: ""
  # X_M: ""
  P2_X: ""
  L2_P2_X: ""
  L1_P2_X: ""

  L2_L1_T: ""
  L2_T: ""
  L1_T_1: ""
  L1_T_2: ""
  # druid forms
  # L1_T_B: ""
  # L1_T_C: ""
  # L1_T_M: ""
  T_1: ""
  T_2: ""
  # druid forms
  # T_B: ""
  # T_C: ""
  # T_M: ""
  P2_T: ""
  L2_P2_T: ""
  L1_P2_T: ""

  L2_L1_C: ""
  L2_C: ""
  L1_C_1: ""
  L1_C_2: ""
  # druid forms
  # L1_C_B: ""
  # L1_C_C: ""
  # L1_C_M: ""
  C_1: ""
  C_2: ""
  # druid forms
  # C_B: ""
  # C_C: ""
  # C_M: ""
  P2_C: ""
  L2_P2_C: ""
  L1_P2_C: ""

  P2_P3: ""
  L2_P3: ""
  L1_P3: ""

  L2_L1_P1: ""
  L2_P1: ""
  L1_P1: ""

  # cancel macro override (has dedicated bind)
  # L2_L: ""

  P2_D: ""

  P2_U: ""

  # mount button overrides
  # P2_R: ""
  # L2_R: ""
  # L1_R: ""
